### ISSUE TITLE
How might we reuse the same component multiple times on a page?

### ISSUE THREAD

**Issue by miguelslp** [cferdinandi/reef#104]
How might we reuse the same component multiple times on a page?
Could a selector return more than one element?

**Test case:** https://codepen.io/miguelslp/pen/VwmaVqg

Thanks!

**Comment by cferdinandi** [comment]
Ooh, that's a good one! As the code is written today, you'd want to create a separate component for each element, but you can centralize the data through a Data Store, and reuse the template through an external named function.

Using your clock as an example, here's how I would approach it: https://codepen.io/cferdinandi/pen/QWGNzjp

Let me do some research on whether or not having one component inject into multiple elements is a good idea or not.

**Comment by miguelslp** [comment]
Okay I will look forward for news on the topic, thank you 😁️ !

**Comment by hovancik** [comment]
I guess I wanted to ask the similar questions: how does one have ie component  `todo` and then another component for `todos` where `todo` are iterated.

**Comment by pwFoo** [comment]
Maybe that should help me too. 
I need to learn how to build my app the "reef way"...

I try to setup routes and change the component based of current route. But it isn't possible to bind a component to a route or get the template...
route "home" render component "home" and route "about" renders component "about".

But maybe it's easier to do?
How to replace template based on current route? Or do I need to wait until this issue is solved?

**Comment by pwFoo** [comment]
Hi @cferdinandi,
template functions may help me with #119. But if some preparation is needed it looks like that:
```
function tpl1(vars) {
    return `My template....`
}
```

And component template part with changeable template function for example based on route:
```
                template: function(vars) {
                    let func = route.template // string with template function name
                    return window[func](vars) // need to improve that I think
                }
```

**Comment by Dan-Do** [comment]
+1 vote from me. I want to mount one component on multiple places on the page.

**Comment by cferdinandi** [comment]
I'm closing this as won't fix, because reef v12 was just released with a totally different API and authoring pattern that negates this question.
