### ISSUE TITLE
How to remove/destroy a Reef component?

### ISSUE THREAD

**Issue by GregOriol** [cferdinandi/reef#107]
Hi,

After adding a Reef component to a page, how do you remove/destroy it? There doesn't seem to be a destroy method. Is it enough to remove the dom object it is on? Is Reef deallocated then?

**Comment by cferdinandi** [comment]
Hi @GregOriol - can you tell me a bit more about the use case or what you're thinking here? 

Reef (in Constructor pattern type libraries in general) don't really have a way to full destroy themselves.

You could set your template to not return anything if a certain property is on it, but it sounds like your more concerned about memory usage in the browser?

**Comment by GregOriol** [comment]
Hi @cferdinandi, I was having the idea to use Reef for some parts of a page, those parts can be opened and closed (think of something like windows): I don't want to use Reef globally for the page because the rendering of the container is done in another way, but locally inside each window/component, plus they are independent technically. So I wanted to be able to clean up when one is closed, including the Reef instance associated with it.

**Comment by cferdinandi** [comment]
@GregOriol that makes sense, and that progressively enhanced approach is exactly the kind of thing Reef was really build for.

Let me give some thought to how components might be able to be garbage collected or "disabled" when no longer needed.

**Comment by cferdinandi** [comment]
Addressed in v12 (now live)

**Comment by GregOriol** [comment]
@cferdinandi Do you mean component.stop()? does it clean things up?

**Comment by cferdinandi** [comment]
@GregOriol A combination of things, really.

Unlike v11 and lower, Reef v12 stores much less information with a `component()` instance. Most information is stored elsewhere. The `store()` and `render()` methods don't create instances at all. 

But I also should have been more clear (I was a bit sloppy in copy/pasting to a few issues) that in JS you can't really remove an instance of a constructor (the `component()` method generates one behind-the-scenes). The best we can do is remove event listeners and such.
