### ISSUE TITLE
Loading async data

### ISSUE THREAD

**Issue by mattburton** [cferdinandi/reef#108]
Love the idea of Reef - in reading the docs about async data I was wondering to myself whether it wasn't something you could do inside of a component as a lifecycle method, so that a component could load it's own data when rendering - maybe something like an optional function you can define like this:
```
new Reef(elem, {
  beforeRender: (elem, data) => {},
  data: {},
  ...
});
```
Then inside of `beforeRender` do my fetch call, etc... updating the component data. Applying this to your example you might wind up with something like this:
```
new Reef(elem, {
  beforeRender: function(elem, data) {
    fetch('https://jsonplaceholder.typicode.com/posts').then(function (response) {
      return response.json();
    }).then(function (data) {
      data.articles = data;
    });
  },

  data: {
    articles: []
  },

  template: function (props) {
    if (!props.articles.length) {
      return `<p>There are no articles.</p>`;
    }

    return `
      <ul>
        ${props.articles.map(function (article) {
          return `<li>
            <strong><a href="#">${article.title}.</a></strong>
            ${article.body}
          </li>`;
          }).join('')}
      </ul>`;
    }
  });
});
```

**Comment by cferdinandi** [comment]
I'm curious, from your perspective, what the benefits of this approach versus the one outlined in the docs are? It also seems like this could maybe be addressed already with [the `reef:before-render` event](https://reefjs.com/api/#reef-events).

**Comment by mattburton** [comment]
I'm looking at Reef as an alternative to React/Vue/Svelte and trying to reconcile the mental model of having self-contained components that can be reused and are responsible for their own lifecycle vs the model of having something else such as the page coordinate the behavior/state of the components. I might be trying to fit a square peg in a round hole of course, so if this doesn't fit in the spirit of Reef then feel free to tell me so :) I guess my other takeaway was the notion of having to filter events to figure out what had changed - hooking into `reef:before-render` makes sense if there's one Reef component on the page, but if there's 4 or 5... I suppose you could have separate event handlers for each component, each checking to make sure the event target was the one it cares about, but it's still getting a bit unwieldy I imagine.

Maybe an alternative would be to have a component instance method like `.on(eventName, ...)` that would allow you to write event handlers that are scoped to that component instance / element?

```
let app = new Reef('#app', {
  data: {
    articles: []
  },

  template: function (props) {
    if (!props.articles.length) {
      return `<p>There are no articles.</p>`;
    }

    return `
      <ul>
        ${props.articles.map(function (article) {
          return `<li>
            <strong><a href="#">${article.title}.</a></strong>
            ${article.body}
          </li>`;
          }).join('')}
      </ul>`;
    }
  });
});

app.on('reef:before-render', function(el, data) {
  fetch('https://jsonplaceholder.typicode.com/posts').then(function (response) {
    return response.json();
  }).then(function (data) {
    data.articles = data;
  });
});
```

Then at least you can avoid the element identity checks, etc...

**Comment by cferdinandi** [comment]
You could achieve the same thing today by passing in an element instead of a selector.

```js
let elem = document.querySelector('#app');

let app = new Reef(elem, {
  data: {
    articles: []
  },
  template: function (props) {
    if (!props.articles.length) {
      return `<p>There are no articles.</p>`;
    }

    return `
      <ul>
        ${props.articles.map(function (article) {
          return `<li>
            <strong><a href="#">${article.title}.</a></strong>
            ${article.body}
          </li>`;
          }).join('')}
      </ul>`;
  }
});

elem.addEventListener('reef:before-render', function (event) {
  fetch('https://jsonplaceholder.typicode.com/posts').then(function (response) {
    return response.json();
  }).then(function (data) {
    data.articles = data;
  });
});
```

To be honest, while I understand the benefit here, it feels a bit "bigger" than what Reef is trying to do.

I'm going to close this as `wontfix` simply because it's out-of-scope for this project, as much as I appreciate why you'd want it. I'm sorry!

**Comment by mattburton** [comment]
Good point re: adding the event listener to the element - hadn't thought of that, and really that achieves the same goal here. No worries - was just an idea that occurred to me while I was looking at the docs - totally agreed that it's out of scope now that I think about it. Thanks for the wonderful library and Go Make Things - longtime listener, first time caller.
