### ISSUE TITLE
Unable to insert into TBODY or TABLE, only a DIV (that contains a Table)

### ISSUE THREAD

**Issue by sansbacher** [cferdinandi/reef#109]
Hi, thanks so much for Reef! (and your daily emails!)

I think this may be related to Issues #21 / #22 but I can't make it work by even if "you remove the existing content from your `thead`". Here's my forked CodePen: https://codepen.io/sansbacher/pen/KKNQMmY
I'm using Win 10 x64, have tried Chrome, Firefox and Legacy Edge - all the same.

If you select '#the-tbody' and return 'insideTBody' it just shows the text, with the HTML stripped. I tried removing existing content from the `TBODY`, from the `THEAD`, removing the `THEAD` entirely, no difference. Same if you select '#the-table' and return 'insideTable' it's the same.

But if you select '#the-div' and return 'insideDiv' then it works as expected (inserting the entire table structure).

I tried allowHTML: true, no difference. I can see my HTML is "correct" (if I manually paste it in the page renders as it should). It's like Reef is stripping the HTML unless it's a DIV, though the Docs/Getting Started guide mention "an element" (which is "typically" a DIV). Must it be a `DIV` only?

It would be nice to be able to insert into an arbitrary element, maybe with a leaveHTML: true option if it's a situation Reef would normally strip HTML. Especially to have place-holder content in the HTML until Reef renders the actual content.

I've found Reef useful and so far I've just made a point to select DIVs and inject all the required HTML.

Thanks again,
   --Saul

**Comment by cferdinandi** [comment]
This is a side-effect of how `DOMParser()` handles certain markup. In it unfortunately not possible to do what you're trying to do the way Reef is build.
