### ISSUE TITLE
Template function 2nd argument is not the route when using addComponent method

### ISSUE THREAD

**Issue by antonioquepasa** [cferdinandi/reef#110]
Hi Chris,

When I add a router to a component, a function used as template will have the router as 2nd argument (the template itself becomes 3rd argument). But that does not seem to be the case when I add the component to the router using addComponent. Should that not be the case? I would expect both approaches to yield similar results.

I tried to put on a reduced test case to illustrate the problem: https://codepen.io/antonioquepasa/pen/abBaepx

In the console, you can see the params as expected (props, route, template) if you attach the router to the component, but not if you add the component to the router (props, template, template again).

Thanks a lot for Reef, very neat tool indeed!

Cheers,

Antoine

**Comment by cferdinandi** [comment]
Good catch. Looking into this.

**Comment by cferdinandi** [comment]
Addressed with v8.2.3
