### ISSUE TITLE
Use of functions in titles in router trigger DOMException

### ISSUE THREAD

**Issue by antonioquepasa** [cferdinandi/reef#111]
Using a function in the title property of a route in the router results in a DOMException.

```
Uncaught DOMException: Failed to execute 'pushState' on 'History': function () { [native code] } could not be cloned.
    at y (https://cdn.jsdelivr.net/npm/reefjs@8/dist/router.min.js:2:2768)
    at g (https://cdn.jsdelivr.net/npm/reefjs@8/dist/router.min.js:2:3259)
    at HTMLDocument.<anonymous> (https://cdn.jsdelivr.net/npm/reefjs@8/dist/router.min.js:2:4406)
```
See console output when clicking on the "chicken" link in this reduced test case for an example: https://codepen.io/antonioquepasa/pen/abBaepx

Also - and maybe these issues are related - using the optional title property for the router seems to have no effect, and so does it for routes added using the addRoutes property (even plain strings).

**Comment by pwFoo** [comment]
I tried to add s "template" property as function to a route object to handle current route easier from component by just call `route.template(vars)`. Maybe dependent to that issue about function in titles.

Would be nice to allow other properties like (custom) template too

**Comment by pwFoo** [comment]
If functions could be allowed here it should solve my problems with specific page templates by route:
```
const router = new ReefRouter({
    useHash: true,
    routes: [
        {
            id: 'teams',
            title: 'Mannschaften',
            url: '/',
            template: function(props, route) {
                return `My custom route template`
            }
        }
    ]
})
```

And used with the component
```
template: function(props, route) {
    // Do stuff...
    return route.template(props, route)
}
```

Would that possible if that issue is fixed?

**Comment by cferdinandi** [comment]
Unfortunately, ReefRouter has been removed from the project altogether, so this won't be addressed.
