### ISSUE TITLE
[Feature request] Bind reactive data and build loops with html attributes?

### ISSUE THREAD

**Issue by pwFoo** [cferdinandi/reef#112]
Hi @cferdinandi,
I coincidentally found your nice reef project and it's similiar to some other small solutions I know. 

Would it possible to add the feature to

1. bind html value / content by attribute like `r-bind="${myvalue}"` or optional (hidden) elements with `r-if="${condition}"`
3. create loops based on html attribute `r-foreach="${myDataArray}"`.  The main element is used as container (for example a <table> tag) and html inside as row template filled by array values? array value could be an object.

I would prefer to keep html templates separated and not mixed up / inline with javascript code. So load templates with ajax, bind values / loops to html elements and use reef to fill and update reactive data and routing urls / pages?

**Comment by cferdinandi** [comment]
I absolutely appreciate the desire for these, but they add a layer of complexity and "done for you" that goes beyond the intended scope and simplicity of Reef.

I'd personally much rather see these hard-coded into the templates themselves, or, in the case of binding, supported via an event listener.

**Comment by pwFoo** [comment]
Hi @cferdinandi,
I took a closer look at the examples and documentation. reef is really great! I think you're right to keep the complexity low! So I need to build some helper around reef for my needs :)

I don't like template strings or small template files with just a `<li>` part for loops. 
Maybe I could try to read the "sub-template" part (children of <ul>) and replace it by reef template / data... But I would need to cache that sub-template for re-render...
