### ISSUE TITLE
Router redirect update url?

### ISSUE THREAD

**Issue by pwFoo** [cferdinandi/reef#113]
I tested router redirect. URL is unchanged, but the redirect destination is loaded. Feels like an page alias and not a redirect?
Would it possible to redirect and push the new route destination url to the browser address bar as optional feature?

**Comment by pwFoo** [comment]
Would be fixed by trigger route / `router.navigate(route)` asked at issue #114

**Comment by pwFoo** [comment]
Found navigate() in source... sorry...

**Comment by cferdinandi** [comment]
I actually like the idea of updating the URL, though. Reopening this. It's a good request.

**Comment by cferdinandi** [comment]
Sadly, router has been removed from Reef, so this won't be addressed. Sorry!
