### ISSUE TITLE
Use 'router:before' event to trigger route redirect

### ISSUE THREAD

**Issue by antonioquepasa** [cferdinandi/reef#115]
Hey Chris,

I am trying to use the 'router:before' event to check if a user is logged (to display his profile) and, if not, redirect him to a login screen using router.visit().

However, I can't seem to be able to prevent the initial route from completing, regardless of the condition. So, the redirection happens but the initial route keeps going and end up being the view displayed.

I tried but had no luck with preventDefault or return. Is there something I am missing?

Thanks!

Antoine

**Comment by cferdinandi** [comment]
Good catch. Just pushed v8.2.4 that should fix this.

**Comment by cferdinandi** [comment]
Specifically, it was not honoring `event.preventDefault()`, and should now.

**Comment by antonioquepasa** [comment]
Thanks a lot for the quick fix! This has been driving me mad for the last few days :-)

I just started to use Reef for the refactoring of a midsize project of mine. So far, it is really cool and I love the simplicity and flexibility of it. I hope you won't mind if I find & report some more bugs in the coming days & weeks.

**Comment by cferdinandi** [comment]
Not at all, please do! And thanks for letting me know about this one. That was a miss on my part.
