### ISSUE TITLE
Polyp check causes uncaught error when nodeType is comment (8).

### ISSUE THREAD

**Issue by zikeji** [cferdinandi/reef#116]
**Test case:** https://codepen.io/zikeji/full/ExZxMqQ

Refer to developer console in the test case. The CodePen "console" does not see this error.

It appears to be an issue with HTML comments. It seems like simply changing the following line in code to ignore nodeType 8 is the solution.

https://github.com/cferdinandi/reef/blob/c4b45eef816c03c13154e0a213f16e8426b3db84/src/_reef/dom.js#L289

```javascript
 return ![3, 8].includes(node.nodeType) && node.matches(polyp); 
```

**Comment by cferdinandi** [comment]
Good catch! Should be fixed with v8.2.5
