### ISSUE TITLE
[Question] Data binding to html elements

### ISSUE THREAD

**Issue by pwFoo** [cferdinandi/reef#117]
Hi @cferdinandi,

short question about data binding to html elements in context to #112.

I have some places in my html layout which need to be filled by template variables. Place `${store.data.value1` doesn't work. So all template variables need to be used with Reef template part from code? So for each single value I need a additional component and attach it?

Something like:
```
const c1 = new Reef('#elem1', {
    store:store,
    template: function(props) {
        return `${props.value1}`
    }
})
```

Each time a try to fill a single value to a small html element? Is that fine because of the count of (small) components? 
Isn't a template part which could be handled by a single component.

**Comment by cferdinandi** [comment]
No, you can set _default_ or _always synced_ values inside any component. https://reefjs.com/advanced/#default-and-state-based-html-attributes

**Comment by pwFoo** [comment]
I know about variables inside of a component. That needs additional components, because the variable is needed outside of a component templates.

Would it ok to use 5 oder 10 components attached to the app to fill some single values of the page? Or may it a performance problem?

I have a index.html file with some base html layout and elements. So HTML isn't returned by a components template! So an additional component or some Javascript to change elements innerhtml.

**Comment by cferdinandi** [comment]
Templates should always return HTML. If you need the properties of a component for use elsewhere, you can access them directly on that components `data` property.
