### ISSUE TITLE
different templates for routes?

### ISSUE THREAD

**Issue by pwFoo** [cferdinandi/reef#119]
My page / content component should set a different template by route.
Maybe I need a template function added to route to return the route specific template?
```
router = new ReefRouter({
  routes: [
    {
      id: 'home',
      title: 'Site Home',
      url: '/',
      template: function(vars) {
        // additional preparation of values or template parts...
        return `my home template...`
      }
    },
    {}
  ]
})
```

Is there a way to define template and use based on current route?
Maybe related to #111 because functions don't work with routes and #104 with re-usable templates.

**Comment by pwFoo** [comment]
Thought about howv to handle route templates from component... 
Simplest option would a switch case to handle all route templates?

I think of would be better and cleaner to allow template property at route object as a function?

So I can Fall route.template(props) to get the current page template?

**Comment by cferdinandi** [comment]
Examples here: https://github.com/cferdinandi/reef/blob/master/demos/router-hash.html

and here: https://github.com/cferdinandi/reef/tree/master/demos/router

Any given route may have multiple components that react in different ways, so templating lives with the components, which receive data about the route.

**Comment by pwFoo** [comment]
Hi @cferdinandi,
sorry, I don't understand how I switch component / template based on route.
Your example just use a route based title?
```
template: function (props, route) {
				return `<h1>${typeof route.title === 'function' ? route.title(route) : route.title}</h1>`;
			}
```

Still no idea how to write client route based templates without switch case...?
```
template: function (props, route) {
    // store used for all data
    switch(route.id) {
        case "home":
            return `Home template ${props.prop1}`
        case "about":
            return `About template ${props.prop3} and some more html template parts, because template is different to home...`
        case "contact":
            return `Contact template is a form and again html is different to home and about... ${props.prop3}`
        [...]
    }
}
```
So I get a hardcoded template function with a case for each page template I use?

I don't see a way to replace / load a different component (or template) based on route?

It would be much cleaner and easier to read with a route given template?
```
template: function (props, route) {
    return route.template(props, route) // no switch case needed...?
}
```

**Comment by pwFoo** [comment]
Also tried to detach / attach components based on current route, but looks ugly too.
Detect the last route, detach that component and load another one.
But both need the same selector destination and mapped to the same variable.

Need a clean and simple way to switch to different page content based on the route. Each page could need a specific template.

**Comment by cferdinandi** [comment]
You can use conditional content in each component, ex.

```js
if (route !== 'home') return '';

return '<h1>Hello, world!</h1>';
```

**Comment by pwFoo** [comment]
I know, but later it looks like that with switch / case or if structure?
```
switch(route.id) {
        case "home":
            return `Home template ${props.prop1}`
        case "about":
            return `About template ${props.prop3} and some more html template parts, because template is different to home...`
        case "contact":
            return `Contact template is a form and again html is different to home and about... ${props.prop3}`
        [...]
    }
```

I searching for a way to have cleaner components with just the needed output / code / templates.

**Comment by cferdinandi** [comment]
You can create a different component for each route and only return anything other than an empty string when the route matches.

**Comment by pwFoo** [comment]
I'm new with that kind of applications based in components.
How "change" detach / attach component based on the current route?
Multiple components with the same selector? Different selector and hide / show elements based on current route?

How would you replace the `#content` part component of the app based on route?

**Comment by cferdinandi** [comment]
Perhaps this may be helpful: https://github.com/cferdinandi/reef/blob/master/demos/router-multi.html

**Comment by pwFoo** [comment]
Thanks! I think I know how to build it that way. With different components! 
I'll do some tests :)
