### ISSUE TITLE
Input content does not update on render

### ISSUE THREAD

**Issue by antonioquepasa** [cferdinandi/reef#120]
Hi Chris,

I find myself stuck in this situation : I have a modal with a login and a password  input fields. If I dismiss the modal, I would like these two input fields to get rid of any data entered.

To this end, I render again the view when closing the modal. It does indeed set all other elements back to their originale state, but the input fields keep anything entered. From what I can see, there is a shadow-root element that seems to get in the way. I confess I know close to nothing to shadow-root. Is this something that can be dealt with from within Reef or do we have to handle this separately?

Just to be accurate: the initial content of the modal is rendered from a template.

Thanks,

Antoine

**Comment by cferdinandi** [comment]
Are you using the Reef HTML attributes listed here: https://reefjs.com/advanced/#default-and-state-based-html-attributes

**Comment by antonioquepasa** [comment]
Hi Chris, I tried but had no luck with them so far. I'll give it another go and will reopen if I still  get stuck. Thanks for the super quick answer!
