### ISSUE TITLE
Encoding issue using Reef.clone

### ISSUE THREAD

**Issue by ThatJu4nGuy** [cferdinandi/reef#122]
I have recently tried to use Reef.clone with a list that containers characters that would require encoding (", :, ' etc). I have found a bug where Reef.clone seems to encode these characters every time it is used. The easiest way to explain this is to view the example I created below:

**Test case:** https://codepen.io/thatju4nguy/pen/MWJqZRj

Perhaps I've missed something but this was definitley an annoying issue to diagnose when I was using reefjs yesterday!

P.S Love the library. Keep up the good work.

**Comment by valterbarros** [comment]
I'm get this problem too

**Comment by valterbarros** [comment]
I solved the problem with the flag `allowHTML` but following the docs it is not recommended. see: https://reefjs.com/advanced/#preventing-cross-site-scripting-xss-attackss

**Comment by cferdinandi** [comment]
Hey y'all... I've got a fix in progress on this one, under the `next` branch.

**Comment by cferdinandi** [comment]
I should have updated this a while ago. Version 10 of Reef addressed this issue by implementing an updated sanitizer under-the-hood.
