### ISSUE TITLE
rendering bug

### ISSUE THREAD

**Issue by zucatti** [cferdinandi/reef#125]
A simple example with ionic vanilla js.
First rendering is OK, after all the page vanished...

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css" />
    <script src="https://cdn.jsdelivr.net/npm/reefjs@8.2.5/dist/reef.js"></script>
</head>

<body mode="md">
    <div id="app"></div>

    <script>
        let app = new Reef('#app', {
            template: function(props) {
                return `
                <div class="ion-page" id="main">
                <ion-header>
                <ion-toolbar>
                    <ion-buttons slot="start">
                        <ion-menu-button></ion-menu-button>
                    </ion-buttons>
                    <ion-title>Rivages 2.1</ion-title>
                </ion-toolbar>
                </ion-header>
                <ion-content> <input /> ${props.clock} </ion-content>
                </div>
                `;
            },
            data: {
                clock: new Date(),
            },
        });
        app.render();
        setInterval(function() {
            app.data.clock = new Date();
        }, 1000);
    </script>
</body>

</html>

**Comment by cferdinandi** [comment]
Can you please provide a reduced test case in the form of a codepen demo?

**Comment by zucatti** [comment]
Thx for reply, here it is :
https://codepen.io/szucatti/pen/JjWOvdy

**Comment by zucatti** [comment]
The reason is the original template is modified afterwards by web components (added class...) so when it is rendered again, it fails because reef compare to the original template and not the updated DOM. A workaround would be to listen to dom changes via mutation observer but how can I bind my original template to events ? Maybe I wrong with this approach...

**Comment by cferdinandi** [comment]
I'd recommend decoupling the Ionic component and the Reef Component from each other. The Reef component should be its own standalone thing.
