### ISSUE TITLE
hierarchical menu samples

### ISSUE THREAD

**Issue by zucatti** [cferdinandi/reef#126]
Hello,
Is it possible to do hierarchical menu with recursive parsing of data ? Can't figure out to do this with reefjs...

Keep up the good work ! ReefJS is awesome

**Comment by cferdinandi** [comment]
Can you please provide an example of what you're trying to accomplish? Thanks!

**Comment by zucatti** [comment]
Thx for the quick reply.
well, I'm trying to do things like that (recursive method in render) :
"data": {
 "menu": {
  "label": "test",
 "menu": {
   "label": "test2" 
  }
}
}

and the ui :
<ul>
  <li>test</li>
  <ul>
    <li>test2</li>
  </ul>
</ul>

**Comment by cferdinandi** [comment]
For that I would personally use a helper function that I run recursively. Here's a demo: https://codepen.io/cferdinandi/pen/PopXExv

And more info on recursion in JavaScript: https://gomakethings.com/recursion-with-vanilla-javascript/
