### ISSUE TITLE
Rendering bug with table and select element

### ISSUE THREAD

**Issue by rrushton** [cferdinandi/reef#128]
I think I have run into a bug. In the supplied example, click the remove button twice. When the two rows are removed the result should say 'No Rows' and it does but there also seems to be a select box left behind for some reason.

https://codepen.io/flippedBit/pen/yLbOwYJ

**Comment by cferdinandi** [comment]
Weird, that does seem to be a bug. Thanks!

**Comment by rrushton** [comment]
I just updated the above Codepen to use v10 and that seems to have fixed the issue. Nice work!

**Comment by cferdinandi** [comment]
Seriously? That's awesome! Pleasant and unintentional side-effect!
