### ISSUE TITLE
Removing dynamic elements list

### ISSUE THREAD

**Issue by valterbarros** [cferdinandi/reef#129]
Steps to Reproduce:

1. Open the test case link
2. Change all selected wizards on the select element
3. Click on remove to remove a wizard list element
4. See that the selected wizard elements are not what we expected

the diff is always removing the last element, the label `Harry Potter - item n` looks working right due to the https://github.com/cferdinandi/reef/blob/eb59a5c9fa412de29dd75bf183a1a6529d0fdb2f/src/_reef/dom.js#L285

I think this https://github.com/cferdinandi/reef/blob/eb59a5c9fa412de29dd75bf183a1a6529d0fdb2f/src/_reef/dom.js#L267-L282 is putting the last list element to the end of the `domMap` and the https://github.com/cferdinandi/reef/blob/eb59a5c9fa412de29dd75bf183a1a6529d0fdb2f/src/_reef/dom.js#L322 is removing him

I fixed this using an index inside my collection like `data = [{name: 'a', index: 0}, {name: 'b', index: 1}]` and use this as id inside the element to create unique dom elements but I think this should be handled by the Reef

**Test case:** https://codepen.io/thevalter/pen/MWmjvdq?editors=1010

**Comment by cferdinandi** [comment]
Sorry for the lack of comment. This does look like a bug. I'll address when I have a moment.

**Comment by cferdinandi** [comment]
Looking into this more, the diffing engine cannot tell the difference between one item and another without a unique identifier.

[React, for example, relies on the `key` attribute for this.](https://reactjs.org/docs/lists-and-keys.html#keys) Reef uses the `id` property instead.

You don't need to include a unique ID your data, per se. You could, for example, convert the item into a valid ID string with a little bit of JS.

```js
return `
      ${props.items.map((item, index) => {
        return `
          <section id="section-${item.replace(' ', '-').toLowerCase()}">
          	...
          </section>`;
```

**Comment by valterbarros** [comment]
what happens if two items have the same name?

**Comment by cferdinandi** [comment]
@valterbarros Do you mean `name` or `id`?

**Comment by cferdinandi** [comment]
Oh I see, you mean name property in the array... IDs should always be unique. What you're describing sounds like a data problem.
