### ISSUE TITLE
Why Router removed?

### ISSUE THREAD

**Issue by aalfiann** [cferdinandi/reef#131]
Why in the latest version 9.x, you removed the Router?

Please tell us the reason...

But actualy I agree with this, cause it will make the size reduced and router feature actualy is not related with reactivity.
So it will better if you create a new plugin for router to separated repository.

Thanks

**Comment by cferdinandi** [comment]
Hi there, great question! A few reasons: 

1. It had some bugs that I didn't feel like addressing
2. I think JS-based routing is bad for the web, and would prefer to encourage folks away from it
3. It distracted from the core value of Reef as a progressively enhanced state-based UI tool

I may in the future look into a standalone option that can be paired with Reef, but for now, there are a handful of other third-party options one can choose from if needed.

**Comment by pwFoo** [comment]
> * I think JS-based routing is bad for the web, and would prefer to encourage folks away from it

So how should it done instead of JS based routing? Would be good to know because I don't used js based routing before and don't know the good ways to build routing for an client side app

**Comment by cferdinandi** [comment]
This is my recommended approach for most folks, @pwFoo: https://gomakethings.com/an-alternative-to-single-page-apps-multi-page-apps-with-service-workers/

**Comment by pwFoo** [comment]
But how handle parts like header, footer or sidebar? JS fetch to get the html file once and from cache each other time? Or do you really repeat hardcoded html parts like logo and basic images?

**Comment by cferdinandi** [comment]
My personal approach is to use a static site generator ([in my case, Hugo](https://gomakethings.com/series/hugo-and-static-site-generators/)) to render the repetitive bits across pages.

A PWA can be a multi-page app. There's nothing about [service workers](https://gomakethings.com/series/service-workers/) that require them to be a SPA, and if anything, using them with an MPA actually eliminates a lot of complexity while providing the same performance benefits.

**Comment by pwFoo** [comment]
Thanks! 
I take a closer look, but think I won't use a static site generator. I'll need a small app (~5 views and some JS parts) with offline / mobile first. Maybe I remove the js router part and create a html page for each view and "include" repeating page parts with fetch requests and JS.  

Should be the easiest way and also flexible, without the need of a js router and benefits from service worker (caching, offline first).

**Comment by antonioquepasa** [comment]
Hi Chris,

I understand you want to keep Reef lightweight and centered on the UI rendering. However, I think ReefRouter is a great addition and I would really encourage you to keep it, even if it is just as a plugin. It would be a shame to lose it altogether. On a personal note, this puts me in trouble as I use it heavily in my project.

Side note: Reef is provided "as is" and I fully acknowledge this fact. However, maybe giving a little heads-up or even engaging the conversation with the Reef community ahead of major changes would be great as they may have consequences. I guess it may be overwhelming for you to have all these requests and expectations from us but this is a sign that we care about Reef and some among us may have time or skill to help it ~~grow~~ prosper. Just sayin' ;-)

**Comment by pwFoo** [comment]
> My personal approach is to use a static site generator ([in my case, Hugo](https://gomakethings.com/series/hugo-and-static-site-generators/)) to render the repetitive bits across pages.
> 
> A PWA can be a multi-page app. There's nothing about [service workers](https://gomakethings.com/series/service-workers/) that require them to be a SPA, and if anything, using them with an MPA actually eliminates a lot of complexity while providing the same performance benefits.

Hi Chris, 
I was wrong... Not PWA... I meant SPA :) And one more question...

With multi page apps I have a normal page navigation, but so each page visit JS code need to be initialized?
I think about a simple fetch based router (trigger sw fetch event) with ajax / js result insertion instead of a "classic" page reload...
Any opinion about performance / ui refresh with a classic page navigation without ajax / SPA?

**Comment by cferdinandi** [comment]
Yes, I think service workers negate the performance concerns. 

Here’s a talk I gave on that very topic: https://gomakethings.com/jsnation/#the-slides-video

**Comment by pwFoo** [comment]
I'll do some tests. Maybe I mix it up... Some parts (edit forms, some additional and maybe overlay views...) may be better loaded by fetch / ajax call and JS, but the basic page navigation could be "classic"... 

Awesome project reef and good talk!!! Thanks! 🥇
