### ISSUE TITLE
Wrong CDN link on website

### ISSUE THREAD

**Issue by rrushton** [cferdinandi/reef#135]
This isn't an issue with reefjs but the website.

The CDN link seems to be incorrect in the example on this page:
[Getting Started Page](https://reefjs.com/getting-started/)

It is: 
https://cdn.jsdelivr.net/npm/reef@10/dist/reef.min.js
but should be:
https://cdn.jsdelivr.net/npm/reefjs@10/dist/reef.min.js

**Comment by cferdinandi** [comment]
Good catch! Updated!
