### ISSUE TITLE
Modifying HTML after render

### ISSUE THREAD

**Issue by Falkan3** [cferdinandi/reef#141]
Hello, 
I'm using Glide.js to mount onto an element, adding some inline styles and event listeners. It works as expected, but on every rerender, all attributes (including inline styles) are stripped, as they are compared using the diff function with template HTML, causing the carousel to break. To circumvent this, I need to reinitialize and mount on every rerender.
Is there a better way to do this?

**Comment by cferdinandi** [comment]
Closing this as won't fix, as reef v12 (now live) uses a more "mostly vanilla JS with a bit of progressive enhancement" approach.
