### ISSUE TITLE
Proxies for reactivity are ruining performance

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/reef#144]
**Reduced Test Case:** https://codepen.io/cferdinandi/pen/VwMpoYQ

If you click the `Swap Wizards` button a few times, it works fine. If you focus on the button and hold the enter/return key down to trigger a swap multiple times, the nested proxy structure overloads the browser and freezes the app.

Switching to [a _setter function_ style approach](https://reefjs.com/advanced/#setters-getters) as the only way to update reactively would dramatically improve performance.

**Comment by pranav-js** [comment]
so this is not fixed yet, right? reactivity wouldn't be using proxies in next release?

**Comment by cferdinandi** [comment]
Correct, but it should be later today. I've got a solution after scouring the interwebz: https://gomakethings.com/better-proxy-performance-in-vanilla-js/

**Comment by cferdinandi** [comment]
Patched in 10.0.1

**Comment by pranav-js** [comment]
@cferdinandi  this library is very light weight and cool. I have some concern like, I want template to come from backend. which means entire block of HTML should come as string and then I am doing to use in render. functions and all should stay in js file only. just the HTML template will come from backend. I have some requirements like I need something like *ngIf in angular, custom attribute if applied to HTML tag shouldn't appear in real DOM based on boolean, or iterate same tag for given array items. Is there any such functionality in reef present? I don't want to separate blocks of HTML into different functions with if else like react. :(

**Comment by cferdinandi** [comment]
@pranav-js please open a new issue for this
