### ISSUE TITLE
Event Listeners not recognised and being removed

### ISSUE THREAD

**Issue by davidbrooksio** [cferdinandi/reef#149]
**Test case:** https://codepen.io/davidbrooksio/pen/poWxgLB (updated to Reef 11)

Hi

I have a strange issue with drag and drop event listeners. I have set up a store, app and component. The app has some event listeners set up and the component is calling these listeners (please see my test case).

The first listener ( ondragstart ) seems to work okay. The second one ( ondragover ) gives and error stating that my function ( dragover_handler ) is not defined. The third listener ( ondrop ) has been stripped completely from the code.

Should Reef 11 work with the Drag and Drop API? Am I missing something obvious (likely)?

Thank you

**Comment by davidbrooksio** [comment]
I've just rebuilt my app and made a couple of minor changes and now the only listener that remains is the `ondragover="dragover_handler(event)"`. The `ondragstart` and `ondrop` attributes are being stripped from the rendered code.

I haven't updated my test case because the current one still shows the issue will but I can if you need me to.

**Comment by davidbrooksio** [comment]
Just so you know, I have added my event listeners to the document and then delegated to the correct html element instead of using Reef built in `listeners` feature. This seems to work fine.

**Comment by cferdinandi** [comment]
I believe this is related to this: https://github.com/cferdinandi/reef/issues/148

**Comment by AlexanderBalson** [comment]
+1 for a way to handle this so that onclick (for example) is not stripped in the html. It would help for some smooth templating for it to leave those in. Loving Reef so far by the way Chris, nice work.
