### ISSUE TITLE
Issues with listeners and multiple on events

### ISSUE THREAD

**Issue by mouse0270** [cferdinandi/reef#152]
ReefJS Version 11.

It appears if you have multiple on events, in my testing I was doing `onfoucs` and `onblur` the second event is missing? When adding a 3rd event, the second one is still missing but the first and last two work...

Its probably easier to just look at the codepen and the console. You'll see that the onclick event is breaking.

https://codepen.io/mouse0270/pen/jOZPXxq

**Comment by cferdinandi** [comment]
Addressed with a redesigned API model in v12 (now live)
