### ISSUE TITLE
Binding input value changes to data

### ISSUE THREAD

**Issue by JoshuaPerk** [cferdinandi/reef#154]
Am I understanding [the documentation](https://reefjs.com/advanced/#html-templates) correctly that this will only bind one-way. Meaning, if the input changes, it will not reflect in the `data.someKeyValuePair`? Has anyone found a clean way to solve for binding a value back to the data object?

**Comment by cferdinandi** [comment]
That's correct. Like Vue and React, Reef is about binding UI to data, but not the other way around.

You can create two-way binding by listening for changes to form data (using the `Element.addEventListener()` method with the `change` event), and updating your data object to match.

[This demo](https://codepen.io/cferdinandi/pen/MWmOrWr) might provide a useful model to follow.
