### ISSUE TITLE
Obj events = {} storing duplicate event listiners causing duplicate calls 

### ISSUE THREAD

**Issue by Topher-Dev** [cferdinandi/reef#158]
There is an issue with addEvent => getListener as the code is deciding whether to add event into Obj events = {};
The comparison of callback === listener.callback is not reliable and allowing "leakage" into this collection causing unreliable behaviour such as the event listener callback running multiple times.

![image](https://user-images.githubusercontent.com/58575021/179091423-38b9d455-b139-4844-bd6b-4a2c0891479a.png)

I've found that the comparison is fundamentally (Believe Highly Likely) one of the string representations between the two. and there are instance where the "Whitespace is not being stored consistantly.

A someone what visual
![image](https://user-images.githubusercontent.com/58575021/179094523-49853faa-37c0-42e7-af5e-983327b42740.png)

I found converting to string expliciltly and removing all white space resolved my issue. of the duplicate records in events ={}. Seems a a bit weird but the solution works.
![image](https://user-images.githubusercontent.com/58575021/179091095-871a0887-3e11-4346-80fa-98e5626fe31b.png)

**Comment by cferdinandi** [comment]
True! Good catch. This was removed in the just-released v12, though, so I'll be closing this issue.

**Comment by Topher-Dev** [comment]
A v12 Very cool, I saw the recent email!

Just curious what were the intentions behind the 'Major overhaul'?

Were you looking to address certain constraints, holes or weakness's of the prior? Or just approach with a different vision with maybe more flexibility?

Having made both does the prior version have advantages over the formers? Trade offs if you will?


Love your work.

Topher
________________________________
