### ISSUE TITLE
Add component.destroy() method

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/reef#159]
Stops auto rending and wipes DOM clean

**Comment by t-lock** [comment]
I'd love to see this! I was thinking about implementing something like an usubscribe method, where you'd detach from processing state changes but keep the component html on page.

I was also considering implementing a "when" method on stores (similar tom mobx) which would allow a one-and-done reaction to a state change that matches the condition, and then stops listenting.

This is a really cool project, appreciate your work here, and I love the direction you went in v12.

**Comment by cferdinandi** [comment]
@t-lock Apologies for being a year late to respond to this one. The things you're asking about are actually already supported in Reef.

- You can [use `stop()` and `start()` methods on the component](https://reefjs.com/api/#component) to stop reactively rendering and restart it, respectively. 
- For manual or one-time updates, you might consider [using a `reef:store` event listener](https://reefjs.com/api/#lifecycle-events), with the `once` property set in the `addEventListener()` options object.

**Comment by cferdinandi** [comment]
The even listener will also allow you to fire side-effects without rendering
