### ISSUE TITLE
Support key for memoization

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/reef#163]
Currently only an `id` can be used. Add support for a `key`, similar to React.

**Comment by duhdugg** [comment]
something like this?

```diff
diff --git a/src/components/render.js b/src/components/render.js
index 265b265..8bedce1 100755
--- a/src/components/render.js
+++ b/src/components/render.js
@@ -212,6 +212,7 @@ function isDifferentNode (node1, node2) {
 		(typeof node1.nodeType === 'number' && node1.nodeType !== node2.nodeType) ||
 		(typeof node1.tagName === 'string' && node1.tagName !== node2.tagName) ||
 		(typeof node1.id === 'string' && node1.id !== node2.id) ||
+		(node1.getAttribute?.call(node1, 'key') !== node2.getAttribute?.call(node2, 'key')) ||
 		(typeof node1.src === 'string' && node1.src !== node2.src)
 	);
 }

```

**Comment by cferdinandi** [comment]
@duhdugg yea, though I don't _think_ you need to the optional chaining operator/`call()` method on that one. I think you can just test it outright since strings and such don't generally make it to the test. I could be wrong.

**Comment by duhdugg** [comment]
I'm having a little trouble following everything that might be passed to it, but I think you're right. The biggest user of this function is the `diff` function, which is used by `render`. There is a possibility that the wrong `elem` argument is provided to render, but this already causes an uncaught exception earlier in the `diff` function as it tries to access the `childNodes` property on a `null` value.

I'll submit a PR with no optional chaining.

**Comment by cferdinandi** [comment]
Added to v13
