### ISSUE TITLE
Use domdiff?

### ISSUE THREAD

**Issue by naasking** [cferdinandi/reef#164]
Not an issue per se, I'm just curious whether you've evaluated the use of the [domdiff library](https://github.com/WebReflection/domdiff). All benchmarks I've seen show it's barely slower than vanilla JS, which is impressive.

I had an idea to implement something like Reef based on domdiff until I came across your project.

**Comment by cferdinandi** [comment]
Is there a compelling reason to remove the existing diffing library in favor of `domdiff()`?

**Comment by naasking** [comment]
You're obviously in the best position to evaluate its suitability, I'm just bringing it to your attention since I didn't see it mentioned in any prior discussions. Off the top of my head:

1. [Performance, as I mentioned](https://krausest.github.io/js-framework-benchmark/2022/table_chrome_106.0.5249.61.html). I haven't seen benchmarks of Reef, but domdiff is actually competitive with vanilla JS. Tough to beat that.
2. Complete and robust. It's well tested and proven being the core of hyperHTML.

I'll leave it there, up to you to decide whether it fits your purposes.

**Comment by cferdinandi** [comment]
`domdiff` has a lot of differences between how Reef's `diff()` method works, most notably that [it doesn't support nested nodes](https://github.com/WebReflection/domdiff/issues/2). That essentially makes it a non-starter for this project.
