### ISSUE TITLE
Using Map or Set as store

### ISSUE THREAD

**Issue by mouse0270** [cferdinandi/reef#167]
Would it be possible to add the ability to use a `Map` or a `Set` as a store in a future version? It appears stores are limited to just `Array` or `Object`.

**Comment by cferdinandi** [comment]
While technically possible, it also adds quite a bit of complexity to the underlying code.

given that the goal of this project is to be simple and feature-lite, I’m not sure the benefits of supporting Set() and Map() are worth that added complexity.

**Comment by mouse0270** [comment]
That makes complete sense.
