### ISSUE TITLE
Lifecycle Events - reef:render is fired on all components in the document

### ISSUE THREAD

**Issue by sjoe77** [cferdinandi/reef#170]
Chris,

This is more of me trying to  understanding on how component rendering works rather than an issue I think. 
[Code Pen](https://codepen.io/sjoe77/pen/xxzMexM)

I have two components todos and chores referencing their respective stores for data. I only change the store for one component but I see a render event for both components in the console.  I thought only the chores component will be rendered after I click the button that adds chore. Can you help me understand this a bit better?

**Comment by cferdinandi** [comment]
Great question! You can fix that behavior by [assigning your store a name](https://reefjs.com/api/#store), and passing in a `stores` option for your `component()`.

```js
let todos = store(['Swim', 'Climb', 'Jump', 'Play'], 'todos');

// ...

component('#todos', todosTemplate, {stores: ['todos']});
```

This scopes the store or stores to specific components, and prevent components that don't use the store from rendering.

[Here's an updated CodePen.](https://codepen.io/cferdinandi/pen/JjZxgdV?editors=0011)

**Comment by sjoe77** [comment]
Thank you for your prompt response!  So only  those components are rendered whose store has changed. 
Recently I saw this issue [162](https://github.com/cferdinandi/reef/issues/162) where you gave an example of how to do Component composition using templates.  If I had a page with parent component I can create component and associate it using the static selector  "#parent" which is the first argument to the component api.
`component('#parent', parentTemplate, {stores: ['parent]});`

However the child components are not components anymore, they are templates. if anything in the parent store changes it will re-render  the parent component and the associated child templates.  The dom-diffing would still surgically apply alterations ONLY to the affected elements which is great!    Is this ok or do you have a better pattern in mind?

BTW I am totally impressed with the minimalist and organic approach here with Reefjs.
