### ISSUE TITLE
How can I create each list item as its own independent reef item?

### ISSUE THREAD

**Issue by Mashiane** [cferdinandi/reef#18]
Thanks for the examples,

I'd like to embed reef elements inside others independently. For example each list item will have more details like image, text, id, class etc.

How can I achieve this ? perhaps with multiple attachTo

**Comment by cferdinandi** [comment]
Exactly. I would probably have the list items get created in the parent Reef instance. Then all of the details can go in the  sub-instance that you attach to the parent.
