### ISSUE TITLE
support disabled and readonly attributes with @ syntax?

### ISSUE THREAD

**Issue by Roguelazer** [cferdinandi/reef#182]
What do you think about adding `disabled` and `readonly` to the attributes that can be set with `@attr="${boolean}"`? They behave pretty much the same way as `selected` and `checked`...

**Comment by cferdinandi** [comment]
I think that's a really good idea!

**Comment by cferdinandi** [comment]
@Roguelazer I was thinking about this more, and... I'm realizing the reason I _didn't_ support functionality like that with these attributes to start with is that they can't really be modified by user interactions like `selected`, `checked`, etc. can be.

Can you tell me a bit more about the use case here?

**Comment by Roguelazer** [comment]
I think I was disabling fields while an HTTP request runs

**Comment by cferdinandi** [comment]
@Roguelazer I think this should work out-of-the-box...

```js
return `<button ${data.disabled ? 'disabled' : ''}>Submit</button>`
```

That said, I'd actually recommend you NOT do this, as disabling buttons that have focus shifts focus to the `document` and creates confusing accessibility issues for screen reader users.

I suggest adding a class that changes the color/opacity of elements _without_ disabling them, and simply ignoring additional submits until the HTTP request is completed, like this...

```js
function template () {
    return `
        <form>
            <!-- form field stuff -->
            <button ${data.submitting ? 'class="disabled"' : ''}>Submit</button>
            <div role="status">${data.submitting ? 'Submitting...' : ''}</div>
        </form>`;
}

let data = store({
    submitting: false
});

document.addEventListener('submit', function (event) {

    // Don't let the form reload the page
    event.preventDefault();

   // If the form is already being submitted, ignore request
   if (data.submitting) return;
   
   // Add data-submitting attribute
   data.submitting = true;
   
   // Do your HTTP stuff...
   
   // Then, reenable the form
   data.submitting = false;

});
```

```css
.disabled {
    opacity: 0.7;
}
```

**Comment by cferdinandi** [comment]
Sorry, I'm closing this as unnecessary given that there's an alternate approach. The boolean hack for `checked` etc. exists primarily as a quick for how user-defined variables work in the DOM.
