### ISSUE TITLE
jsdoc issue

### ISSUE THREAD

**Issue by thomaswormann** [cferdinandi/reef#183]
Hi Chris,

I think you forgot to update your jsdoc on one of your latest changes here:

https://github.com/cferdinandi/reef/blob/9552836ffe8fb9b18c97272a184b473ae14ad5d1/src/components/render.js#L57-L64

In the jsdoc you reference events as a boolean, later your accessing it as a object:

https://github.com/cferdinandi/reef/blob/9552836ffe8fb9b18c97272a184b473ae14ad5d1/src/components/render.js#L70-L73

And I think the problem starts at the diffAttribute function, where events is declared as a boolean as well:

https://github.com/cferdinandi/reef/blob/9552836ffe8fb9b18c97272a184b473ae14ad5d1/src/components/render.js#L103-L109

And no jsdoc regarding events here at all:

https://github.com/cferdinandi/reef/blob/9552836ffe8fb9b18c97272a184b473ae14ad5d1/src/components/render.js#L160-L164

Cheers,
Thomas

**Comment by cferdinandi** [comment]
Good catch, thanks! I'll get that updated soon...

**Comment by cferdinandi** [comment]
This was fixed at some point. I forget which version, though, sorry!
