### ISSUE TITLE
Listeners remove html attributes

### ISSUE THREAD

**Issue by davidbrooksio** [cferdinandi/reef#184]
**Test case:** https://codepen.io/davidbrooksio/pen/PoXeEwg

It's all there in my test case but the crux of it is that as soon as I add the listener code (for example `let events = listeners({ log });`) certain attributes are arbitrarily removed from the rendered html. My test case shows that the class has been removed from the spans and also some of the `data-` attributes are removed but weirdly some `data-` attributes remain.

I'm happy to submit any more information if required, just let me know.

**Comment by davidbrooksio** [comment]
Hi again. I realise that is project is maintained by one guy (@cferdinandi) so I understand that fixes can sometimes take a long time and that's fine, it's "free" software after all. I was just wondering if this project is still being developed?
It's fine if it isn't I just need to know if I should look elsewhere or hold out for a fix.
Thank you.

**Comment by cferdinandi** [comment]
@davidbrooksio it is, but I've had 0 time to look into this issue. Thanks for the reduced test case. I can clearly see the issue in action. I'll try to debug this soon.

**Comment by davidbrooksio** [comment]
Hi @cferdinandi, thank you for your reply. I know what it's like maintaining projects and juggling everything else so I hope you don't think I was being pushy. Please let me know if you need me to test anything.

**Comment by cferdinandi** [comment]
@davidbrooksio Alright, just pushed version 12.3.2, which fixes this issue. Thanks for letting me know about it!
