### ISSUE TITLE
How to read a signal's data built via a store?

### ISSUE THREAD

**Issue by paulrouget** [cferdinandi/reef#190]
```js
let todos = store({ x: 42 }, /* some setters */)
```

I guess I have to do: `todos.value.x` ? I was expecting `todos.x` to work, or at least to have `value` documented somewhere? Or should I also add getters along the setters? Or am I missing something?

Also, the codepen is outdated and use the old version API.

**Comment by paulrouget** [comment]
> Afaict `todos.x` does work? Both with `store()` from v12.x and `signal()` from v13.0.0.

Ah, I must do something wrong:

```js
let {store} = reef;

let todos = store({ x: 42 }, {})

console.log(todos.value.x); // 42
console.log(todos.x); // undefined
```

> > Also, the codepen is outdated and use the old version API.
> 
> Looks like it's using `signal()` to me, unless it was just changed. ;-)

From https://reefjs.com/advanced/#stores:

Isn't that outdated: [Try store action functions on CodePen →](https://codepen.io/cferdinandi/pen/oNaYoWV?editors=0011) ?

**Comment by Frenzie** [comment]
> Ah, I must do something wrong:

Maybe you're using a really ancient version? Double check if your wires are plugged in. ;-)

> Isn't that outdated

Yes, I was talking about https://codepen.io/cferdinandi/pen/wvmoPMg

**Comment by cferdinandi** [comment]
Good catch! This is an oversight in the docs.

For data `store()` objects, the data you get back is immutable and has to be accessed on the `value` property. This ensures that the _action_ methods don't collide with the data and provides a way to ensure the data can't be overwritten directly.

I'll update the docs to properly document this.

**Comment by cferdinandi** [comment]
Fixed the docs!
