### ISSUE TITLE
Add option to keep attributes on nodes with [reef-keep]

### ISSUE THREAD

**Issue by vvvkor** [cferdinandi/reef#194]
Could be useful for `details` and `dialog` nodes with reactive content and natively controlled `[open]` state.

render.js:
```
if (!('hasAttribute' in node && node.hasAttribute('reef-keep'))) diffAttributes(node, existingNodes[index], events);
```

**Comment by cferdinandi** [comment]
@vvvkor can you say a bit more about this and how it would differ from `[reef-ignore]`?

**Comment by vvvkor** [comment]
Sorry for being unclear. Maybe I have missed something.
As far as I can see, contents of the node with `[reef-ignore]` will not be reactive, no updates on render.
I thought that it would be good for nodes with native interactivity to have an option to render updates of inner contents, and still keep the attributes of the node itself to preserve its open/closed state.
What I suggest is to skip diffing of attributes but continue to diff contents of nodes marked with `[reef-keep]` or something like that.

**Comment by cferdinandi** [comment]
Interesting! Let me think on this a bit. I'd be curious to see if it works as expected with things like the `dialog` element, DOM libraries, etc.

My gut tells me that after those are rendered, you generally want some other script to handle them in their entirety, but I'm open to being wrong.

**Comment by vvvkor** [comment]
Seems to work correctly in major browsers with `details` and `dialog`.
[Demo](https://vvvkor.github.io/reef/reef-ignore.html)
More testing is required, of course.

Whether you want to control them with some other script - probably depends on project requirements. But it may be convenient to be able to work reactively with the same data source within interactive elements. For example, to edit some item in modal dialog. Looks like Reef with this little tweak can handle it without additional scripts.

**Comment by cferdinandi** [comment]
If you want to dynamically render the contents of a some nested content, you can technically create a new `component()` for that element or manually run `render()` as needed (I've done this on a project or two).

While I do see the value in what you're suggesting, it feels like an edge case that can be readily solved with the existing tools and that adds more complexity and "places for things to go wrong" in the code base.

I'm leaning towards _not_ adding support for it.

**Comment by vvvkor** [comment]
Understood. Anyway, thank you for consideration.

**Comment by cferdinandi** [comment]
@vvvkor As always, though, I'm open to being persuaded otherwise! I'm just trying to weigh a few factors before adding things.

**Comment by vvvkor** [comment]
Reef's ideology is to be small and simple. And this is what I like about it. Pleasure to dig in.
So, I'm not going to insist. You are damn right to be careful before adding features for edge cases.

**Comment by cferdinandi** [comment]
Closing based on our conversation
