### ISSUE TITLE
onclick attribute removed by reef

### ISSUE THREAD

**Issue by th-developer** [cferdinandi/reef#195]
in a template function which generates links with an attribute onclick="..." this onclick does not appear in the resulting HTML document.

https://codepen.io/th-developer/pen/dyaGJZa

Thank you :-)

**Comment by cferdinandi** [comment]
That’s correct. For security reasons, it’s added as an `on*` property on the element itself, and will work as expected.

**Comment by cferdinandi** [comment]
I should also add, this assumes that you are registering your event handlers per the documentation: https://reefjs.com/advanced/#events

**Comment by th-developer** [comment]
Ah!   Thank you very much for your help
