### ISSUE TITLE
Reef types

### ISSUE THREAD

**Issue by mvestnik** [cferdinandi/reef#197]
+ issue #86
Hi! 
This project needs typescript. TS greatly speeds up the development process and allows you to understand the code. There are a lot of tools to make writing easier and faster, such as ide hints, TS linters, etc

This example work:

![1.png](https://github.com/cferdinandi/reef/assets/150515091/3de85c72-3b0c-4169-b452-982a52927704)

This is not work and TS could have explain this:

![2.png](https://github.com/cferdinandi/reef/assets/150515091/b1bc727e-34a9-4ec8-b1a7-63fbe2951903)

This not work: 

![3.png](https://github.com/cferdinandi/reef/assets/150515091/c08cda0e-9eb0-4089-b922-72e7552623c9)

Wrong func signature, why? 

![4.png](https://github.com/cferdinandi/reef/assets/150515091/37984d8f-460c-416e-b6c7-969b38037b0d)

I found many more examples 

Without refactoring and types, this project will remain a very cool idea but with poor implementation

**Comment by cferdinandi** [comment]
No, sorry. It’s an unnecessary dependency.

**Comment by cferdinandi** [comment]
Also fuck off

> but with poor implementation

**Comment by orionrush** [comment]
Ahh Chris my man, slow your roll pirate!
He’s obviously a prick, but you’re a leader.

Much love, Ben


Sent on my mobile device ... 100% typo guarantee

M: +44 (0) 796 456 5153
orionrush.com
instagram.com/orionrush
twitter.com/orionrush
