### ISSUE TITLE
Component composition

### ISSUE THREAD

**Issue by stephanebisson** [cferdinandi/reef#199]
Is there a way to do component composition, defining smaller components to be used within larger components? 

For example, is it currently possible to refactor the To-do app into a structure of components like this, each with its own rendering logic and events handling:

- TodoApp
  - TodoList
    - TodoItem
  - TodoForm

**Comment by cferdinandi** [comment]
No there's not (by design). You can use nested functions that return HTML strings to provide a bit more structure to your code if you'd like, but this library is deliberately different from how something like Vue or React might handle UI.

**Comment by ozanmuyes** [comment]
[This answer](https://github.com/cferdinandi/reef/issues/162#issuecomment-1198458028) might be valuable in this case.
