### ISSUE TITLE
Reactive data (feature)

### ISSUE THREAD

**Issue by Heydon** [cferdinandi/reef#2]
Reef looks good! I love anything that can do heavy lifting without loads of bloat, dependencies, and compiling.

I note that—and I think I'm correct in saying—an event is emitted when the `render()` function is used. But it would seem no event or 'reaction' occurs when the data itself is changed. 

I read https://vuejs.org/v2/guide/reactivity.html and it appears Vue does this by converting the basic `data` object into getters and setters which emit events whenever the values change. I've been playing with something similar which just wraps assignment in functions to emit a `customEvent`: no need for setters or getters, and works with adding properties.

I solved this in just under 1K uncompressed: https://gist.github.com/Heydon/9de1a8b55dd1448281fad013503a5b7a. But I wonder if there is a better way. Have you considered adding this facility, so that authors could (conditionally) subscribe to changes in the data object?

**Comment by cferdinandi** [comment]
Oh man, if you have this figured out, that would golden!

I do worry about the overhead here, and also, quite honestly, wonder if Reactivity is really more desirable than explicitly updating the DOM. But I'm quite open to this idea.

**Comment by cferdinandi** [comment]
Looking at your approach, btw, it looks like you'd then need to use custom methods to update data, yes?

In my ideal world, I can just using vanilla JS methods for pushing items to an array or adding/removing things from an object. I don't like to have to think about it.

**Comment by Heydon** [comment]
@cferdinandi True, and I think that's why Vue works with getters and setters: the setter changes the value but fires an observable event as a side effect. The problem I found was that you can't name a setter the same as a standard property. Using `data.num = 5` with the following example creates an infinite loop...

```js
data = {
  num: 4,
  set num(val) {
    this.num = val;
    // Fire CustomEvent here
  }
}
```

I've not got round this yet, but open to ideas! I'm new to object getters and setters.

**Comment by cferdinandi** [comment]
@Heydon from looking into this a little, a think a lot of the overhead in Vue is also spent looping through the data and adding all of the getters and setters.

I'm just not sure manually calling `render()` is a big deal, and I can actually see it as a feature to some folks.

**Comment by Heydon** [comment]
@cferdinandi You could well be right. Couterpoint: whenever the data changes, relevant UI certainly has to be updated. Do you think render() would end up having to be appended to most functions in the app? I'm honestly not sure, but it's a concern.

**Comment by cferdinandi** [comment]
@Heydon Totally with you. Data changes === UI updates in many (most? all?) situations.

However.. there may be multiple state updates that you want to happen before that render takes places.

Making `render()` something you run manually means that:

1. You as the developer can control when that happens, instead of letting your framework automatically decide for you.
2. Significantly reduces the size and complexity of Reef.js.

**Comment by plauk** [comment]
Point in favour of having this as an option: Prototyping. Being able to automatically update the UI as soon as data changes speeds up initial setup time. I can imagine starting a project with the UI updating automatically and then changing over to manual render calls later on to improve control.

**Comment by cferdinandi** [comment]
@Heydon After doing some more [reading about how this works in Vue](https://hackernoon.com/how-to-build-your-own-reactivity-system-fc48863a1b7c), I think this is a feature I probably won't be adding.

The short version: it would significantly increase the size of the script to the point that I'd say, "Just use Vue," or, "Just use React."

**Comment by cferdinandi** [comment]
Change of heart! This feature is coming in the *very* near future.

It will work like React's `setState()` feature, allowing you to pass in partial or complete state changes and have them automatically re-rendered into the DOM. I'm also adding a getter function to let you get a cloned version of the existing state.

**Comment by Heydon** [comment]
@cferdinandi Nice! I like the sound of that.

**Comment by cferdinandi** [comment]
Annnnnnddddd data reactivity is here! https://github.com/cferdinandi/reef/#state-management
