### ISSUE TITLE
13.0.3 has broken attributes on html

### ISSUE THREAD

**Issue by davidbrooksio** [cferdinandi/reef#203]
**Test case:** https://codepen.io/David-Brooks/pen/MWdgKmY

Please take a look at the test case above. You will see that I have added 2 classes to the html (in the JS) and each time the page updates the classes are removed and re-added. This is probably a poor example because at least in the case the classes are re-added, in reality the page loads with no attributes on the html and therefore breaks the css on the page.

I'll create another demo as well...

**Comment by cferdinandi** [comment]
Thank you! Fixed with v13.0.4
