### ISSUE TITLE
Is the store function doesn't work with component?

### ISSUE THREAD

**Issue by aalfiann** [cferdinandi/reef#205]
Hi, 
is the store function doesn't work with component?

I follow to your documentation link >> https://reefjs.com/advanced/efficient-dom-diffing/

The problem is, there is no any result in html view.

I use the latest of ReefJS v13.

**Test case:** https://jsfiddle.net/aalfiann/4qzvjhap/9/

**Comment by cferdinandi** [comment]
@aalfiann With the `store()` method, you can only update data using setters functions, and have to access the data from it using the `.value` property.

Here's an updated test case with working code: https://codepen.io/cferdinandi/pen/zYQBMLr?editors=1011

And thanks for pointing out the docs. They need to be updated with the new `signal()` method. That was an error on my part.
