### ISSUE TITLE
Web Component rendering issues with signal and/or component

### ISSUE THREAD

**Issue by tmm6907** [cferdinandi/reef#208]
**Test case:** https://codepen.io/terrence-moore-the-bashful/pen/xxoLaVx
Sorry for the late post, had to rewrite it since the other code is at the office. Having issues with component rendering and styling rendered html. I'm not sure if it is signal that is causing my issue or component. In a previous component, I was able to get things working when i used store instead of signals but I have seen the signals work, however if it works, its only for one paint it seems because none of the updating occurs. The only way I've been able to get this particular component working is to swap out the html without using the signal. I tried render as well, that didn't result any differently than component.
Using Windows and Chrome.
I filled out the codepen and pinned it, not sure if that worked or not, never submitted anything on there before.

**Comment by cferdinandi** [comment]
@tmm6907 There's a lot going on here, but at a high level: you're mixing traditional DOM manipulation and state-based UI, and it's creating conflicts. 

If you're going to render the UI with Reef, you should _always_ control the UI with Reef. If you're going to manipulate it with other means, always use those. (This is true of tools like React and Vue as well).

Your state and the template are the sources of truth. Anything you do via `.innerHTML` or whatever to one of those child elements will just be overwritten whenever Reef renders again.

**Comment by tmm6907** [comment]
Right, I understand that, in the codepen, if you comment out the line where I set the innerHTML ( it's only being set in one location), it no longer works even though, from my understanding, it should work with the component() line alone

**Comment by cferdinandi** [comment]
@tmm6907 Gotcha. Could you please do me a favor and create a [reduced test case](https://gomakethings.com/the-power-of-the-reduced-test-case/) that shows just the minimum required functionality, with the bug actually occurring? 

I'd like to see the Reef-specific issue so that I can help you solve that.

**Comment by tmm6907** [comment]
I figured it out. I have to add the event listener to the document. That's why it would look like component was only doing an initial render but wouldn't register updates. Thank you for your help!

**Comment by tmoore411** [comment]
Just wanted to add, been loving your library, A year ago I wouldn't have even considered myself a frontend developer and now, your library + web components have gotten me excites about the frontend. Your course work is great too
