### ISSUE TITLE
Data driven reef components

### ISSUE THREAD

**Issue by VanquishedWombat** [cferdinandi/reef#23]
Hi - reef looks really cool. I am just getting into it so this may already be possible. Be gentle...

I have a query / enhancement request around creation of complex HTML layouts.

My use case is a data-driven form. Lets say I get my form definitions from a server, and in the first case I have a title, four inputs and a submit button in the form, but the next form definition might have 5 inputs and 2 buttons. 

Following your documentation for nested components,  the initial reef object would need to reference the id's of each of the objects that the form definition requires me to produce.  However, I do not know ahead of the execution what those id's will be. 

As a parallel, in jquery, I would use .after(), .before(), .append() and .appendTo() to target new elements into the DOM in such a case. 

I realise reef is intended to be kept skinny but I think maybe adding those 4 jquery-like functions, or at least .append() and .appendTo() would allow sophisticated component build-up via programmatic and therefore data-driven means.

A potential solution would be to parse the form definition and create speculative placeholder divs in the html for the initial reef object. However, my long term goal is to allow the form spec to be richer and allow nesting, in which case the optimum approach is the full append/appendTo method. 

Sorry I am not skilled enough to fork the code and make my own attempt at a solution.

Regards.

**Comment by cferdinandi** [comment]
To be honest, I'm not 100% sure what you're trying to do, but... it _sounds_ like the kind of thing that you could use [the `attach()` method](https://github.com/cferdinandi/reef#attaching-and-detaching-nested-components) for.

You would create your form, and then when the data you need comes in you, you can create a new Reef instance and attach it to the parent component.

**Comment by VanquishedWombat** [comment]
Yep sorry that wasn't a very granular description. After sleeping on it and re-reading the doc on the github page I have decided that I do not grok attachTo().  

What confuses me is the fact that I can pass it an array of reefs. This is outlined in the [Nested components](https://github.com/cferdinandi/reef#nested-components) section of the docs. 

I am probably thinking about it in the wrong direction, but my initial expectation is that when nesting components and because I read attachTo() as being in the context of the child, that you would attach a child to its parent. So a parent can have many children but a child only has one parent - kind of the standard tree-root structure we know from the html DOM, for example.  Which implies that attachTo() would take as its sole parameter the parent reef object.

So - could you explain a bit more about the intention of passing an array to attachTo().

I am attempting to illustrate the intended HTML structure and code it using reef in this codepen https://codepen.io/JEE42/pen/MWWepBX?editors=1010. It is embryonic in terms of the reef/js code but the hard coded html will give an explanation of a use case.

Appreciate you taking the time to respond.

**Comment by cferdinandi** [comment]
@VanquishedWombat You've got it reversed. It's `parent.attach([childElems, ...])`. 

You call `attach()` on the element you want to attach your sub-components to, and pass those components in. A parent element could have multiple sub-components, hence the array support. If you only need to attach a single element, you can pass it in without the array.

**Comment by VanquishedWombat** [comment]
ok - that makes sense thanks. Could I beg your indulgence for a little longer and ask the same question on the use of attachTo which is a parameter passed into the new Reef() function. In the Github doc the example shows an array with a single reef member being passed in, example:

````javascript
// Nested component
var todos = new Reef('#todos', {
	data: app.data,
	template: function (props) {
		var html = '<h2>Todo List</h2><ul>';
		props.todos.forEach(function (todo) {
			html += '<li>' + todo + '</li>';
		});
		html += '</ul>';
		return html;
	},
	attachTo: [app]  // <---- why the array ? 
});
````

**Comment by cferdinandi** [comment]
@VanquishedWombat In a word: flexibility.

It's a less common use case, but imagine that you had a component that was inside another component (in this case, `app`). Then imagine that instead of using the `app.data` as it's data source, it used [a *lagoon*](https://github.com/cferdinandi/reef#create-a-lagoon) as its source of truth.

There are two times when you would want this component to re-render:

1. If `app` was re-rendered
2. If the lagoon (or external data source) was updated

Allowing you to attach a sub-component to multiple Reef objects supports that kind of flexibility in a way that a single attachment could not.

Admittedly a bit of an edge case, but trivial to support, so...
