### ISSUE TITLE
Template String Conversion into HTML Nodes drops <style> Nodes

### ISSUE THREAD

**Issue by semmel** [cferdinandi/reef#24]
This is due to `DOMParser.parseFromString(template)` puts any `<style>` tags into the `<head>` of the returned document. When Reef's internal `stringToHTML` function returns `doc.body` the markup in the head is lost. 

**Test case:** https://codepen.io/semmel-semmel/pen/LYYLPym
When clicking the button `reefApp.setData` will update the custom element's dom, however it looses the [inline styles inside the web component](https://css-tricks.com/styling-a-web-component/#article-header-id-2), because `stringToHTML` drops all `<style>` nodes. Thus text looses it's colour.

A fixed in `stringToHTML` could be
```javascript
// ...
// If DOMParser is supported, use it
if (support) {
	var parser = new DOMParser();
	var doc = parser.parseFromString(str, 'text/html');
	doc.body.prepend(...doc.head.childNodes); // <--- Added this line
	return doc.body;
}
//...
```

Does this make sense?

**Comment by cferdinandi** [comment]
I can't speak to shadow DOM elements, but... with a more traditional approach, it's working exactly as I'd expect: https://codepen.io/cferdinandi/pen/poowvxM

**Comment by semmel** [comment]
A single call to `app.render()` is not the problem, neither is the shadow dom - that is just to illustrate why I need `<style>` inside my component.

The problem is `stringToHTML` which is called before the dom diffing. The first `app.render()` does not call ` stringToHTML`. That's why also my example everything is fine *until* you *update* the dom via `app.setData()` which then before diffing the dom calls `stringToHTML` that misses the `<style>` and thus the colour style disappears with the update.

You can see that if you inspect the element in the developer tools before and after clicking the button. The update is supposed to just change some text content but it removes all inlined `<style>` completely.

**Comment by cferdinandi** [comment]
Ah yep... here we go: https://codepen.io/cferdinandi/pen/rNNwMeE

I see it now.

**Comment by cferdinandi** [comment]
Sorry took me a bit to get to this, but fixed with https://github.com/cferdinandi/reef/releases/tag/v4.1.9

**Comment by semmel** [comment]
@cferdinandi 
> Sorry took me a bit to get to this ...

No need to apologise, Open Source projects should be fun first - obligations last! 😄
