### ISSUE TITLE
Element Attributes without a Value are not Updated

### ISSUE THREAD

**Issue by semmel** [cferdinandi/reef#25]
**Test case:** https://codepen.io/semmel-semmel/pen/LYYLOwE
The button in the test case should be disabled after the 2 second delay.

**Reason for this behaviour**:
When adding attributes to the element in the internal `addAttributes` function, the code `elem["disabled"] = ""` seems to silently (without exception) fail.

**Possible fix**:  Use [`Element.setAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) because `elem.setAttribute("disabled", "")` works just fine.

**Comment by cferdinandi** [comment]
Thanks! Will look into this. I appreciate the reduced test case.

**Comment by cferdinandi** [comment]
Fixed with https://github.com/cferdinandi/reef/releases/tag/v4.1.7
