### ISSUE TITLE
When some component's DOM element transitions from "empty" to "some content", it goes to the parent element instead

### ISSUE THREAD

**Issue by rdromao** [cferdinandi/reef#26]
Something strange is happening when a DOM element inside a component transitions from "empty" to "some content": that "some content" is appended to the parent instead of being appended to the element.

Here's a simple CodePen: https://codepen.io/rdromao/pen/MWWPrGz

I think this line:
https://github.com/cferdinandi/reef/blob/ce0d8cc52c69a6badeacafc7188e6c06eeb64fd9/src/js/reef/reef.js#L404

... should be:
`domMap[index].node.appendChild(fragment)`

Right? 🤔

**Comment by davy7125** [comment]
@rdromao I experienced the same bug. Thank you for the provided fix, it works for me ;-)

**Comment by aiibe** [comment]
No PR ?

**Comment by cferdinandi** [comment]
Fixed with v4.1.6. Thanks!
