### ISSUE TITLE
event-handlers are stripped from template

### ISSUE THREAD

**Issue by tiptronic** [cferdinandi/reef#27]
Using an event-handler inside a template doesn't work

`<li class="list-item" onclick="clicked('${item}')">${item}</li>`

where 'item' == 'image/test.jpg'
is transformed to:

`<li class="list-item">image/test.jpg</li>`

**Comment by cferdinandi** [comment]
That's a feature, not a bug. `on*` events in templates are a security risk and are stripped out. You can use a regular old event listener for this. `addEventListener()`

https://gomakethings.com/event-delegation-and-multiple-selectors-with-vanilla-js/

**Comment by tiptronic** [comment]
Hm - I'd rather let the user chose to add sanitizing...

For me this renders this neat project useless, since I don't need sanitizing, but speed, as I operate solely on my own data. Too bad :( 

If you look at e.g. `marked` (https://marked.js.org), they removed sanitizing for just this reason. Imo that's the right approach.

**Comment by cferdinandi** [comment]
Cool. Use that project instead. 😎

**Comment by cferdinandi** [comment]
Had a change of heart on this. Fixed with https://github.com/cferdinandi/reef/releases/tag/v4.1.7
