### ISSUE TITLE
Template literals

### ISSUE THREAD

**Issue by mindplay-dk** [cferdinandi/reef#29]
I like the basic ideas and line of thinking behind this library, but I'd like to suggest you consider using template literals.

The approach of internally serializing all values to HTML strings, and then parsing them and turning them back into HTML elements, isn't very efficient.

Not having access to the original data within the template isn't very practical - for example, if you have a Markdown string you want to render, you first need to unescape the HTML value, which didn't need to be escaped in the first place.

Having a single option `allowHTML` to disable the encoding of *all* of the data isn't very helpful either, since a single component could contain a mix of data types: raw strings, HTML, Markdown, numbers, booleans, objects, etc.

(It looks like you've gone back and forth on the idea of pre-escaping data between major releases of the library, so I guess you're aware of some of the problems with this approach.)

Also, the strings approach is limited to updating HTML serialized string-attributes, as opposed to updating properties of HTML element objects, e.g.:

    template: ({disabled}) => '<input ' + (enabled ? "" : "disabled") + '>'

As opposed to e.g.:

    template: ({disabled}) => html`<input disabled=${ !enabled }>`

In practical terms, you might consider using (or supporting or integrating) something like [`htm`](https://github.com/developit/htm), which generates fast rendering functions.

Alternatively, you might consider writing a basic HTML5 parser, which is [surprisingly easy](https://gist.github.com/mindplay-dk/5167cf7e123064c287c65174593a52ab) and would allow you to completely bypass unnecessary encoding/decoding of HTML - while allowing natural things like inline event-handlers, style object literals, booleans, etc. like JSX allows, but using browser standards.

I do realize this precludes *native* IE support (without transpiling) but at some point [94%](https://caniuse.com/#feat=template-literals) has to be good enough, right? 😉

In summary, the biggest problem with this library, as I see it, is the idea that everything must be turned into strings before it can get to the DOM - this isn't efficient or practical and, in a sense, the barrier between template functions and the browser object model currently is almost as high as it is between the browser and the server; in my opinion, with a client-side library, the template needs to be much closer to the DOM/BOM than this.

Also, per the README, "It doesn't have a Virtual DOM", which is true as far as the external API - but it does [internally](https://github.com/cferdinandi/reef/blob/master/src/js/reef/reef.js#L420-L425) use the equivalent of a virtual DOM model.

In terms of the total round-trip from template to DOM, this is effectively more steps than a virtual DOM: from data values to HTML-escaped strings, to DOM objects via `DOMParser`, to your internal "details" model (the "virtual DOM") and then finally diffing to the live DOM objects.

Compare this with a traditional virtual DOM approach, which doesn't have the escaping or `DOMParser` steps - which makes me think, with something like `htm` in the mix, this would already be faster, simpler, and much closer to the DOM, in terms of templates mapping directly to HTML object properties, rather than taking the whole HTML escaping/parsing round-trip. (Also, `htm` can be optionally [compiled away](https://github.com/developit/htm/tree/master/packages/babel-plugin-htm) for even smaller footprint, if desired.)

If you want to truly avoid the virtual DOM step internally as well, as mentioned, you might consider a custom HTML5 parser - which might mean a bit more initialization overhead per template, but should yield substantially faster updates overall. (I'm happy to post a bit more information on this idea, if requested.)

Either of these approaches could also pave the way for proper support for components, possibly with life-cycles. (I know your stated mission is for this library to be an *anti-framework*, but have you tried manually managing the life-cycles of nested components? If every child component is a global instance as shown in the README, that's easy - but if you have something like a custom drop-down or date-picker, and have to manually manage the life-cycles of component instances, this quickly gets out of hand.)

I think you have some nice ideas, but the basic idea of treating everything as strings causes too many practical problems.

Anyhow, this is just my personal analysis after some quick testing. Cheers! 🙂

**Comment by cferdinandi** [comment]
This is already supported. From the list of features:

> Simple templating with JavaScript strings or template literals.

**Comment by cferdinandi** [comment]
Sorry, giving your comments a more thorough read now, some additional comments:

> Also, the strings approach is limited to updating HTML serialized string-attributes, as opposed to updating properties of HTML element objects, e.g.:
> 
> template: ({disabled}) => '<input ' + (enabled ? "" : "disabled") + '>'
> As opposed to e.g.:
> 
> template: ({disabled}) => html`<input disabled=${ !enabled }>`

So, again, you can use template literals already, making your second syntax doable already.

It's completely up to the end user of this how they want to handle that.

As for the internal structure, performance, etc., Reef comes from a place of "make it simple to use" and being "good enough."

The way it works right now provides a super tiny file size that loads and renders an initial view faster than Vue or React. Subsequent renders work plenty fast enough for a typical site or app. If you're building Facebook or Twitter sized apps (and realistically, almost none of us are as much as we'd like to think we are), another tool might be a better fit.

**Comment by mindplay-dk** [comment]
> So, again, you can use template literals already, making your second syntax doable already.

Well, of course you can use HTML strings *produced* by a template literal - that's not a feature "supported" by the library, it's just how the user chooses to produce the HTML string.

That doesn't work for inserting anything other than string attributes though - and it doesn't work for properties of any other type than strings.

I'm talking about [tagged](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates) template literals, which would require a factory function of some sort with a simple parser, which would be able to support DOM object properties of types other than strings.

If you don't understand the difference, you might want to take a look at some of the references I posted.

**Comment by cferdinandi** [comment]
Just to clarify, [this kind of templating](https://github.com/developit/htm) is one of the main reasons Reef exists. I think it's terrible and needlessly overcomplicated.

**Comment by mindplay-dk** [comment]
"needlessly overcomplicated" at 600 bytes? 🤷‍♂️

**Comment by cjkoepke** [comment]
For what it's worth, complexity and byte size are not related.

**Comment by cferdinandi** [comment]
I’m referring to ease of use for developers who aren’t comfortable with or interested in the class syntax. 

Anywho, we’re done here.
