### ISSUE TITLE
Needs npm package

### ISSUE THREAD

**Issue by pinkhominid** [cferdinandi/reef#3]
Hi Chris, I'm following your work on reef and it looks really nice and lean. I'd like to npm install this but 'reef' is being used by another package. Curious if you could mention your plan here. Maybe scoping, @cferdinandi/reef?

**Comment by cferdinandi** [comment]
No plan. Won't be publishing on NPM.

There's a semantically versioned CDN you can pull from, though.

**Comment by pinkhominid** [comment]
Had a feeling you would say that. Thanks!

**Comment by cferdinandi** [comment]
Sorry! I know a lot of folks like and use NPM, but... as this is one of a few dozen projects I actively, an additional `npm publish` every time I make updates adds a surprising amount of mental overhead.

**Comment by pinkhominid** [comment]
No worries. This works, `npm i -S cferdinandi/reef.git#v0.0.6`. Only thing that's lost is accepting a range.
