### ISSUE TITLE
Reef with reactive CSS background-image

### ISSUE THREAD

**Issue by Reforced** [cferdinandi/reef#42]
Hi Chris!

First thanks for this lightweight tool for the toolbox! I run into a bit of trouble with updating elements with a background image. Reef does not seem to like inline CSS, even with allowHTML set to true.

Consider my test case: https://codepen.io/Reforced/pen/vYNaPeN

As you see it keeps "jumping". Using inline `style="background-image: url('${data.images[0]}');"` does not work; it seems to be getting escaped to just https, without anything of the URL.. Any ideas about how to approach this better?

**Comment by cferdinandi** [comment]
I see what you mean. Appears to be a bug. Will look into this asap.

**Comment by cferdinandi** [comment]
Fixed with v7.1.3.

Just an FYI: the flash in your demo is happening because you used `setInterval()` instead of `setTimeout()`, so it's resetting the template to empty divs every 2 seconds. A render event fires, and the background images are added again.
