### ISSUE TITLE
The Live Typer demo is no longer working.

### ISSUE THREAD

**Issue by sreekotay** [cferdinandi/reef#46]
**Test case:** https://codepen.io/sreekotay/pen/dyYqjQP
Loads "true" by default and then oddly echoes typing.

Tested against 4b1aad9af166b42be3aa8d01594d4c6628bdc025 (master at the moment)

**Comment by cferdinandi** [comment]
Reduced test case: https://codepen.io/cferdinandi/pen/WNQdvQK

**Comment by cferdinandi** [comment]
Fixed with v7.1.5
