### ISSUE TITLE
Can't set multiple data properties at once

### ISSUE THREAD

**Issue by BinaryMoon** [cferdinandi/reef#47]
The new method for updating data makes my code a lot smaller but there's a few instances where I would like to set multiple properties at once to avoid re-rendering the templates many times.

**New** (render template multiple times):
```
unsplashImageList.app.data.mode = 'list';
unsplashImageList.app.data.data = results;
```

**Old** (render template once):
```
unsplashImageList.app.setData(
    {
        mode: 'list',
        data: results,
    }
);
```

Another example is setting the default properties for the app. My app has the option to reset the app properties so I was previously using:

```
ninjaData.setData( { ...ninjaDataDefault } );
```

but switching to:

```
ninjaData.data = { ...ninjaDataDefault };
```

does not work, which suggests I will need to set each property individually, and this will render each component 7+ times.

**Comment by cferdinandi** [comment]
I should make the docs more clear here. Reef batches updates, so when you do this...

```js
unsplashImageList.app.data.mode = 'list';
unsplashImageList.app.data.data = results;
```

...Reef only renders once. It will batch updates those together.

> For better performance, multiple property updates may be batched into a single, asynchronous render. You can detect when a render has been completed using the `render` event hook.

For ease when updating more than two properties, you can also use the `Object.assign()` method to update them in one swoop (requires a polyfill for IE).

```js
Object.assign(unsplashImageList.app.data, {
        mode: 'list',
        data: results,
});
```

**Comment by BinaryMoon** [comment]
Ah ha - thank you. That helps.

**Comment by cferdinandi** [comment]
Anytime, and great question!
