### ISSUE TITLE
Introducing.... Reefer ;)

### ISSUE THREAD

**Issue by sreekotay** [cferdinandi/reef#48]
Hey Chris Thoroughly having fun with ReefJS ... (just discovered it earlier this week! :))
.... and had a fun notion for making it declarative.

```
    <script type='reef/hello' rfp-greeting='Yo :) Yo'></script>
    <script type='reef/wizard' rfp-selected='neville'></script>
    <script type='reef/typer'></script>
    <script type='reef/nested'></script>
    <script type='reef/todos' rfn-target='#todos'></script>
```
Check out: https://codepen.io/sreekotay/project/editor/ZvkWPj# 

hello-world.html is just your simple hello world. 
hello-world-reefer.html is what it looks like with Reefer! (declarative reef).

Then next-world-reefer.html just shows your other examples with reefer.

I'll likely add store support and then release as a standalone project. Note that it works with vanilla Reefer -- no changes required (though I have a few suggestion)...

Not really an issue - but curious for thoughts/suggestions...

**Test case:** https://codepen.io/sreekotay/project/editor/ZvkWPj#

**Comment by sreekotay** [comment]
Oh I should mention - I *did* extend the Reef semantics to add "listeners".  There is only one call to addEventListener per document (per event type) but it handles the boiler plate stuff for Reef Components....

**Comment by cferdinandi** [comment]
Not my personal style of coding, but really neat! PS: I dig your avatar!
