### ISSUE TITLE
Reef Not defined when attempting to import the router via ES Modules

### ISSUE THREAD

**Issue by k5nn** [cferdinandi/reef#55]
I'm following the tutorial for using the ESM method cause I want to use snowpack and two things

https://codepen.io/k5nn/pen/oNjKYpM

1. Importing Reef via ESM does not append to the window I need to add it manually 

when you open up the inspect element the window object does not have Reef in it but when you add
`window.Reef = Reef`
before the console.log it appears

2. Importing Reef Router via ESM returns the error Reef is not defined

Minor Issue with snowpack ( I don't know if I should bring it up here since it seems like the solution is for router.js to have it's own package.json but I might as well bring it up for future reference ) when attempting to do regular snowpack install

`npx snowpack install` 
it only picks up reef not the reef router but when you need the router also you need to create your own config

snowpack-config.json
`
{
	"install" : [
		"reefjs" ,
		"reefjs/router"
	]
}
`

then install with snowpack via 
`npx snowpack install --config ./snowpack-config.json`

**Comment by cferdinandi** [comment]
With ES modules, components are never attached to the `window`. Built-in scoping is a specific feature of how they work.

Similarly, they will only work if the `script` element that's importing them has the `type="module"` property on it.

You can use a module bundler to compile ES modules into a "traditional" JS bundle/IIFE that will attach to the window if you need that.
