### ISSUE TITLE
Feature: Efficient update adjacent nodes

### ISSUE THREAD

**Issue by CheloXL** [cferdinandi/reef#56]
Great project. Love the DomDiff.
One thing that I think may be improved is the updating of same-kind adjacent nodes. Right now, if I insert (for example) a new LI node at the beginning of a UL list, since the diff algorithm doesn't has any context, it doesn't knows that the list can be moved down instead of have to update every single LI element AND adding a new LI at the end.

On a library I'm working on (not related) I faced the same problem with objects, where I could not equate them using `==`, so I had to resort to some identifier of the object (usually a property named _id_).

I think that maybe you can also use the same approach, by using a custom attribute/data attribute. What are your thoughts on this?

**Comment by cferdinandi** [comment]
Something I've struggled with a bit myself. I'm not sure what the right approach is, but it would be nice to be able to do. I'm gonna leave this open until I have a better sense of how I'd approach it.

I don't think you can trust a unique ID since the user could override it, and I don't think I want to add attributes/properties to the DOM that the user didn't themselves code in.

**Comment by CheloXL** [comment]
Well.. I was thinking on the user (developer) be responsible of the attr, not the library. So I can create the attr based on some internals. And of course, if I change the attr, or delete it, it is because I _should_ know what I'm doing :)

**Comment by boulaya66** [comment]
We could extend the way we use Array.prototype.map with that piece of code :

```javascript
let seed = 1;
const genID = () => seed++;

function mapWithKey(items, key, cb){
  const getKey = (item) => {
    if (typeof key === 'function')
	return key(item) || genID();
  else
    return item[key] || genID();
  }
  return items.map((item, index) => cb(item, getKey(item), index, items), items);
}
```

Then, it's up to the developer to use it or not within his data structure and template:

```javascript
...
   data: {
    todos: [{id:11, do:'Swim'}, {id:1, do:'Climb'}, {id:2, do:'Jump'}, ...]
  },
  template: function (props) {
    return `
      <ul>
        `${mapWithKey(props.todos, 'id', (todo, key) => 
          `<li data-id="${key}">${todo.do}</li>`).join('')}`
      </ul>`;
  }
...
```
Finally, within `diff` algorithm, you could check for a childNode.dataset.Id prop and wether present or not choose the right strategy.

**Comment by cferdinandi** [comment]
Wanted to provide an update here: I've got an idea on how to address this, at least partially.

Currently, if the existing UI has more elements than the template, Reef just chops the extra UI elements out of the UI before diffing. Similarly, if the new UI has more elements, it just replaces them inline as it diffs.

A _smarter_ way to handle this would be to check the element type while diffing, and if they _don't_ match, insert a new element before it and keep going. Then, handle removing extras at the end.

This should in theory cut down on massive UI updates.

It doesn't exactly address the ordered list situation like you've got going on there, and I do need to figure out something there. I don't want to add any attributes to the UI that don't exist in the template, but I'm sure there's a way to make this work, too.

**Comment by cferdinandi** [comment]
Again, just thinking aloud on this:

> It doesn't exactly address the ordered list situation like you've got going on there, and I do need to figure out something there.

Setting IDs, even internal ones, doesn't help much since when the template changes I still need to map that to real UI. I think the solution for sequential elements of the same type is going to involve comparing things like ID and `innerHTML`. It won't be perfect, but it will be a start.

**Comment by CheloXL** [comment]
Setting internal ids will help you determine if a node has been moved, deleted or added.

First render:
```html
<ul>
    <li data-reef-id=1>...</li>
    <li data-reef-id=2>...</li>
    <li data-reef-id=3>...</li>
</ul>
```
Second render
```html
<ul>
    <li data-reef-id=4>...</li>
    <li data-reef-id=3>...</li>
    <li data-reef-id=2>...</li>
</ul>
```
You can easily see that node 3 has been moved, node 1 has been deleted and node 4 has been added.

When I created the issue, I was thinking in this kind of modifications (that are the most common). Not, for example, moving one of the `li` from one `ul` to another `ul`.

**Comment by cferdinandi** [comment]
It doesn’t though. On the second render, either the IDs will all be different, or a new node injected in the middle of the existing ones would get the idea of an element that’s already in the UI.

this wouldn’t work any differently than what already happens now.

**Comment by cferdinandi** [comment]
What I mean is, the item with the id of 4 in your example would actually be given an idea of 1. There’s absolutely no way for Reef to give that an ID of 4 unless the user specifically provided one in the template

**Comment by CheloXL** [comment]
Basically, when you start diff-ing, you create a map of nodes with data-reef-id attrs and their positions inside its parent and later you scan that map for changes when you pass a new rendered view.

(you answered too fast...)

But that's why I said that it is up to the developer to add those attributes. He will know from where to obtain those ids so they match on each render.

**Comment by cferdinandi** [comment]
But reef has to convert the template string into HTML elements to do the diffing. 

The “internal map” wouldn’t help here at all.

**Comment by cferdinandi** [comment]
Oh, and having a developer add them: that’s really no different than them adding IDs or some other unique non-custom attribute.

if the idea is to have the library handle this automatically, forcing the developer to add custom attributes to every element seems to work against that goal.

**Comment by CheloXL** [comment]
Of course that you can't do that. It is impossible to do that (assign the ids automatically) from your code (reef). I get that, and only what to provide the developer a way to do that so he can optimize updates.

Yes, the internal map helps (to speed up lookups). You first create the map using the actual dom and then use that map to optimize the diff. Without the map you would need to have two loops for each parent node (old/new) to check for changes in position.

**Comment by CheloXL** [comment]
Not to every element, just to list collections.

**Comment by cferdinandi** [comment]
Ah! So... if the developer is going to assign a unique ID, I think having them assign an actual `id` property instead of a custom one would be preferable, personally.

**Comment by CheloXL** [comment]
> Ah! So... if the developer is going to assign a unique ID, I think having them assign an actual `id` property instead of a custom one would be preferable, personally.

Yes. I used the data-reef-id as example, but of course the id attribute could be also used as well. I generally use data-* attrs because it's easier to check if that's an ID my library uses, as opposed to a standard attr that can be there for whatever reason.

For this particular case, for example, I would expect that ALL nodes that are part of a list to have the data-reef-id attribute to be handled correctly (usually you render those lists using a loop, so that should not be a problem).

**Comment by cferdinandi** [comment]
Alright, v8.1.0 should address this.

Under-the-hood, when comparing two DOM nodes, Reef now...

1. Checks to see if the items are the same node type, and if so, if they have the same ID (if they both do not have an ID, that would be considered "having the same ID"). 
2. If they "are the same node" per the conditions above, their content and attributes are diffed as normal (same way its always worked)
3. If they're a different node (different type or ID), Reef checks to see if the right node exists further in the DOM tree.
4. If it does, Reef moves it to the correct spot
5. If not, Reef injects a new DOM node

**Comment by CheloXL** [comment]
Question: The moved node, once moved, is then "diffed"?

I mean, since you are moving the node into a position that it is always after the current waked node, does that imply that the moved node will be also updated if I updated its position and something else inside it (like a title, for example)?.

**Comment by cferdinandi** [comment]
After the node is moved, it's further diffed to check for any changes in attributes, content, sub-nodes and so on.
