### ISSUE TITLE
Child component does not detach from parent

### ISSUE THREAD

**Issue by benrudolphWSP** [cferdinandi/reef#58]
https://codepen.io/benrudolphwsp/pen/abdwjbO

When trying to detach a child component from a parent component using a button causes error: 

![image](https://user-images.githubusercontent.com/36246631/85742446-7c15c900-b6c0-11ea-9ead-1a10dcd79e51.png)

- Reef v7.3.0
- Windows 10 1909
- Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by cferdinandi** [comment]
Fixed with v7.3.1
