### ISSUE TITLE
Reef pollyfill version throws "Invalid operand to 'in': Object expected" error in IE11

### ISSUE THREAD

**Issue by brudolph** [cferdinandi/reef#60]
Getting the following error in IE11 using the polyfill version of Reef.

```
Unhandled promise rejection TypeError: Invalid operand to 'in': Object expected
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid operand to 'in': Object expected",
      message: "Invalid operand to 'in': Object expected",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Invalid operand to 'in': Object expected
   at stringToHTML (eval code:755:5)
   at Reef.prototype.render (eval code:814:3)
   at Anonymous function (eval code:738:28)
   at Anonymous function (eval code:32:7)
   at forEach (eval code:16:3)
   at renderPolyps (eval code:736:3)
   at Reef.prototype.render (eval code:818:3)
   at displayData (eval code:174:3)
   at _callee$ (eval code:63:13)
   at tryCatch (eval code:43:7)"
   }
```

For me at least, the `str` argument being passed into `stringToHTML` is empty.

**Comment by cferdinandi** [comment]
Can you please attach or share your code? I know the code pen won’t run and IE, but seeing your code might help me figure out what’s going on.

**Comment by brudolph** [comment]
Definitely. Here you go. https://codepen.io/benrudolphwsp/pen/abdwjbO

**Comment by cferdinandi** [comment]
I had a hunch about what the problem was, and for once, it was actually right!

Template literals, which you were using in your template function, do not work in Internet explorer. If you switch to concatenated strings, they should start working.

**Comment by aalfiann** [comment]
@cferdinandi 

> Template literals, which you were using in your template function, do not work in Internet explorer. If you switch to concatenated strings, they should start working.

I didn't understand what is concatenated string in template?
Could you give me the example working and not working?
I have the same problem. 

This is my code and having same invalid **operand to in** in IE11

Original Code before using babel ES5
```
var app = new Reef("#app", {
  data: {
    msg: ''
  },
  template: function (props) {
    return `<div class="message">
    	${props.message}
    </div>`;
  }
});
```

After converted by Babel
```
var app = new Reef("#app", {
  data: {
    msg: ''
  },
  template: function template(props) {
    return "<div class=\"message\">\n    \t".concat(props.message, "\n    </div>");
  }
});
```

But still got error **operand to in** in IE 11.

**Comment by cferdinandi** [comment]
Reduced test case please

**Comment by aalfiann** [comment]
You can see directly to my website at https://imgproxify.com/status

I've use the latest reef.min.js and reef.polyfills.js

Here is the code before converted using babel
```
https://imgproxify.com/assets/js/status.js
```

Here is the code after converted using babel
```
https://imgproxify.com/assets/js/status.test.js
```

**Comment by cferdinandi** [comment]
Sorry, for clarity, a reduced test case is not a WIP progress, but rather a demo with the minimum amount of code and content required to reproduce the problem: https://css-tricks.com/reduced-test-cases/

**Comment by aalfiann** [comment]
I found it. The problem is the type is wrong at switch case..

**Comment by cferdinandi** [comment]
The power of the reduced test case! 😊

**Comment by aalfiann** [comment]
@cferdinandi 

I found the real problem causes invalid operand to 'in' 

The reduced case test >> https://jsfiddle.net/aalfiann/3sq65ebL/

Actual problem is we can't return empty string in IE11.

Or maybe I miss something?

**Comment by cferdinandi** [comment]
@aalfiann Thanks for that test case! Just pushed version 7.6.2, which should address this bug.
