### ISSUE TITLE
Problem with classes and state

### ISSUE THREAD

**Issue by DaviUchoa** [cferdinandi/reef#62]
**Test case:** https://codepen.io/daviuchoa/pen/jOWKNZX?editors=1010

Hello, I have a problem here, let's see, 

When I try to pass an object to reef component's data (state) the object's methods aren't recognized.

It is always returning `TypeError: "x" is not a function`. But if I try to use the "x" function outside the Reef component it works.

If I can help you to solve this you can send me a message. I'm available to for any kind of help

Thanks in advance, Reef is a nice lib.

**Comment by cferdinandi** [comment]
`hero` has no `whoIAm` property or argument. That's a function in the `IronMan` class.

**Comment by DaviUchoa** [comment]
Hi @cferdinandi ,

There is a typo on the code pen, I already fixed, sorry.

But the error persist, I'm using the 
```
let hero = new Hero() 
console.log(hero.whoAmI())
```

The var `hero` is a instance of Hero class, this method cannot be accessed inside the props?

**Comment by cferdinandi** [comment]
The `Hero` class and the `props.hero` are two separate things. There's still no `whoIAm()` method in the `heroComponent`.

**Comment by DaviUchoa** [comment]
I understand, but is there anyway to use classes inside the state and use its public functions/instance vars?

**Comment by cferdinandi** [comment]
Yes and no.

Data that lives as part of a Reef component state gets converted into a Proxy, so if you're using the component's `data` property, that should be where the data actually lives.

If you want, though, there's no reason why you can't use data from external objects/classes inside your `template` function. Don't try to use `props` for them. Call them directly.

You'll lose out on reactivity this approach, though, and need to call the `render()` function explicitly.
