### ISSUE TITLE
Gaining access to route rendered on the 'render' event

### ISSUE THREAD

**Issue by ThatTonybo** [cferdinandi/reef#64]
Any way to hack in support to get a route property on the render event? Or is there something like it already there? I need access to know what route was rendered, if possible.

**Comment by cferdinandi** [comment]
Great question! There are two ways to do this:

1. The `current` property on your `router` will return the details about the current route, including the ID, URL, and any parameters. This was missing from the docs, so I just added it here: https://reefjs.com/routing/#current
2. [The `routeUpdated` event](https://reefjs.com/routing/#routing-events) will always fire immediately after the `render` event (and after the render has happened). Unlike `render`, which can fire for both routing events and general state updates, `routeUpdated` only fires when the route changes. It's intended as a hook to add/remove scripts, event listeners, and other route-dependent code. The current route is included with the `event.details`.

**Comment by ThatTonybo** [comment]
Awesome, thanks so much.
Got one last question quickly, 404 routes (I have a `*` route set-up) aren't firing when I directly navigate to the link first time, but works fine when using `<a>` links and related. Bug or intended behavior?

**Comment by cferdinandi** [comment]
Related to https://github.com/cferdinandi/reef/issues/52 maybe?

**Comment by ThatTonybo** [comment]
Looks like it pretty much. Is there a fix in progress for it?

**Comment by cferdinandi** [comment]
Documented in the issue. You need to configure your server to redirect all requests to your index.html file.

**Comment by ThatTonybo** [comment]
It's a Reef issue, I've already got the `*` path pointed server-side to send index.html on any request.

**Comment by cferdinandi** [comment]
Link? Source code?
