### ISSUE TITLE
Does Reef remove element event listeners?

### ISSUE THREAD

**Issue by kittykatattack** [cferdinandi/reef#68]
Just a question: When Reef removes elements from the DOM, does it make sure that all its event listeners are removed as well? Just a small concern about memory leaks and was wondering what Reef is doing to help prevent them.

Thanks!

**Comment by cferdinandi** [comment]
No, it does not, but browsers themselves do garbage collect event listeners attached to events that no longer exist. 

I strongly recommend using event delegation, however: https://gomakethings.com/why-event-delegation-is-a-better-way-to-listen-for-events-in-vanilla-js/

**Comment by kittykatattack** [comment]
Thanks @cferdinandi! Event delegation is the approach we're taking for now 😄.

From what I've read it seems like even with modern browsers there's still a small chance for memory leaks if events aren't explicitly removed before removing DOM elements, so I'm not taking that risk at the moment. Event delegation seems the way to go.
