### ISSUE TITLE
Asyncronous data fetching

### ISSUE THREAD

**Issue by ThatTonybo** [cferdinandi/reef#71]
What would be the best way to do asynchronous fetching of data from say, a back-end server?

On the home/index page, I plan to show a loading indicator (such as data placeholders), make a GET request to the API, and replace the data on the front-end when the request succeeds (or fails). I've got an existing store and a prop set as an empty array, and I just need to add the data from the back-end to that array.

Thanks!

**Comment by brudolph** [comment]
Hello @ThatTonybo! Couldn't you just use a promise to fetch your data then once returned render your reef app? I can show you an example if you are interested.

**Comment by ThatTonybo** [comment]
> 
> 
> Hello @ThatTonybo! Couldn't you just use a promise to fetch your data then once returned render your reef app? I can show you an example if you are interested.

That'd be great if you could show me an example, sure. Didn't really think of just doing it like that.

**Comment by cferdinandi** [comment]
I really outta put up a demo of this on the ReefJS website... let's keep this open until I do.

But until then, here's a demo for you: https://codepen.io/cferdinandi/pen/yLJrMaV

**Comment by cferdinandi** [comment]
And in case that Pen ever disappears...

```html
<h1>Articles</h1>
<div id="app">Loading...</div>
```

```js
// Create an app
var app = new Reef('#app', {
	data: {
		articles: []
	},
	template: function (props) {
		return `
			<ul>
				${props.articles.map(function (article) {
					return `<li>
						<strong><a href="#">${article.title}.</a></strong>
						${article.body}
					</li>`;
				}).join('')}
			</ul>`;
	}
});

// Fetch API data
fetch('https://jsonplaceholder.typicode.com/posts').then(function (response) {
	return response.json();
}).then(function (data) {
	app.data.articles = data;
});
```

**Comment by ThatTonybo** [comment]
Sweet, honestly that's exactly what I'm after personally, and it'd be a great thing on the website for sure. Under the Advanced section possibly?

**Comment by cferdinandi** [comment]
That's a good place for it, yea. I should probably also add it to the demos page

**Comment by ThatTonybo** [comment]
Random question by the way (asking here instead of opening another issue), I'm unable to get my Reef app to work on Google Chrome. Been testing in Firefox and it's fine, but when I open in Chrome I get a blank page and this error:
```
site.js:24 Uncaught TypeError: Cannot read property 'id' of undefined
    at s.template (site.js:24)
    at s.render (reef.min.js:2)
    at reef.min.js:2
```
Line 24 is me using the following code in the `template` function:
```js
if (route.id === 'index') {
```
I logged `route` (the template function uses `function (props, route) {` as used in examples) and it seems to be fully undefined. What's up there? Chrome specific bug?

**Comment by cferdinandi** [comment]
If you have a demo I'd be happy to take a look, but I would recommend opening a new issue for that.

**Comment by ThatTonybo** [comment]
Alright, I'll get some code sorted on a pen and open a new issue later for you on it.

**Comment by cferdinandi** [comment]
added to the site
