### ISSUE TITLE
Certificate on web site expired Nov 21 2020 and is now invalid

### ISSUE THREAD

**Issue by rouilj** [cferdinandi/reef#75]
‎Looks like your let's encrypt update didn't happen. Current cert for https://reefjs.com/ expired on
Saturday, ‎November ‎21, ‎2020 10:48:30 according to Firefox and openssl s_client -connect reefjs.com:443

CONNECTED(00000004)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = reefjs.com
verify error:num=10:certificate has expired
notAfter=Nov 21 15:48:30 2020 GMT
verify return:1
depth=0 CN = reefjs.com
notAfter=Nov 21 15:48:30 2020 GMT
....
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3037 bytes and written 415 bytes
Verification error: certificate has expired

**Comment by cferdinandi** [comment]
Not sure how that failed, but fixed now. Thanks!

**Comment by rouilj** [comment]
My pleasure. I am moving away from jquery to vanilla javascript as part of my tracker for roundup. Your site has been very valuable. I have been looking at using reef for some components of the refactor. Have a great weekend from a fellow Bostonian.
