### ISSUE TITLE
How to apply events directly on the template tags?

### ISSUE THREAD

**Issue by fabienrohrer** [cferdinandi/reef#79]
Probably I missed something, but it seems to be impossible to create a clean `onclick` events directly on the template tags while it's a basic feature in React:

``` js
import Reef from 'reefjs';

class View {
  constructor() {
    let app = new Reef('#app', {
	template: `<button onClick={() => this.doSomething()}>Click me</button>`
    });
    app.render();
  }
  doSomething() {
    console.log("clicked");
  }
}

let v = new View();
```

Test case: https://codepen.io/DrGivago/pen/KKgdoyw

Instead, global click events are used in the demos, I have issues with this poor solution.

```js
document.addEventListener('click', clickHandler, false);
```

Is there a way to do what I would like in a cleaner way?

**Comment by cferdinandi** [comment]
Respectfully, the way React does it is stupid. It reinforces bad developer habits and increases memory load in the browser.

That said, you can use `onclick` events on elements the same way you would do it in plain on JavaScript: https://codepen.io/cferdinandi/pen/poEjLxg

**Comment by cferdinandi** [comment]
For reference, in case the codepen ever goes down:

```js
var app = new Reef('#app', {
    data: {
        clicked: 0
    },
    template: function (props) {
        return `<button onclick="clickMe()">I've been clicked ${props.clicked} times</button>`;
    }
});

function clickMe () {
  app.data.clicked++;
}

app.render();
```

**Comment by fabienrohrer** [comment]
Thank you for your kind and precise answer; even if it's annoying for my project, it makes perfectly sense.

**Comment by cferdinandi** [comment]
Calling it "kind" is generous 😂😂😂

**Comment by fabienrohrer** [comment]
I'm not a React developper 😄
