### ISSUE TITLE
Router addRoutes don't works

### ISSUE THREAD

**Issue by ecanuto** [cferdinandi/reef#80]
Router addRouter don't works as expected. If you look at console on test case you can see that third console.log still prints only two elements.

At first, we can think that problem is with arrays since addRoute with object "seems to work" but event with object route don't works. Only routes added on initialization works. Looks like something related with property "_route" or some kind of clone on middle of process, I am trying to debug.

**Test case:** https://codepen.io/ecanuto/pen/gOweLxZ

Also, in addRoutes, this code:

```js
	var _routes = this.routes;
	if (type === 'object') {
		_routes.push(routes);
	} else {
		_routes.concat(routes);
	}
	this._routes = _routes;
```

could be:

```js
	var _routes = this.routes;
	if (type === 'object') {
		_routes.push(routes);
	} else {
		this._routes = _routes.concat(routes);
	}
```

_routes.push already added to this.routes and Array.concat returns concatenated array.

But even with this changes, Router.routes still showing always first value from constructor because we don't  have a routes property. Still investigating and working on a PR but maybe you can be faster than me ;-)

**Comment by ecanuto** [comment]
This looks to be the problem:

```js
routes: {value: Reef.clone(_routes, true)},
```

@cferdinandi any reason to use clone here?

**Comment by ecanuto** [comment]
Also, current is calculated on constructor, that is why it don't works using addRoutes. I will work on a PR tonight since now I understand what happens. Still, don't understand the reason to user Reef.clone.

**Comment by cferdinandi** [comment]
Good catch on that one. I `clone()` the routes because I never want the user to be able to directly modify the routes object.
