### ISSUE TITLE
Reef.emit and Reef.debug guidance please

### ISSUE THREAD

**Issue by davidbrooksio** [cferdinandi/reef#82]
**Test case:** https://codepen.io/davidbrooksio/pen/vYXRwLp

This isn't a bug, I just need some help with the Reef.emit and Reef.debug functions.

Please see my test case (above) where I am obviously using these functions incorrectly because they don't seem to do anything. Are you able to offer some guidance as to how to call these two functions? I feel that I am missing something obvious but can't figure it out.

Thank you.

**Comment by cferdinandi** [comment]
Updated demo: https://codepen.io/cferdinandi/pen/yLaKmEZ

Debug mode throws errors more aggressively. For example, let's say `#app2` isn't an element. Normally Reef ignores it and moves on. With debug enabled, it throws an error.

`Reef.emit()` immediately emits a custom event. You typically want to run it when something happens in your app.

In your demo, you don't setup an event listener until after your event runs, so there's nothing to listen for. The event has already happened.

**Comment by davidbrooksio** [comment]
Hi Chris, that's great thank you for your help :)
