### ISSUE TITLE
Reef Types

### ISSUE THREAD

**Issue by shockdevv** [cferdinandi/reef#86]
https://www.npmjs.com/package/@types/reefjs

@cferdinandi
I don't mean to be rude, so It's up to you whenever you want to have a repository for it or not. I can help! Routes types will be available soon. 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50443 
Made sure to include you as owner as well.

**Comment by cferdinandi** [comment]
I'm sorry, I don't really understand what this is

**Comment by shockdevv** [comment]
> I'm sorry, I don't really understand what this is

Typescript type definitions. 

https://www.typescriptlang.org/docs/handbook/2/type-declarations.html

**Comment by cferdinandi** [comment]
Oh, yea, I have no interest in maintaining or supporting that. I’m not a Typescript fan. Sorry!
