### ISSUE TITLE
Diffing compared to other libraries ?

### ISSUE THREAD

**Issue by GregOriol** [cferdinandi/reef#87]
Hi,

Thanks for your cool implementation: it's a really nice take on a very common problem, and your solution is pretty!

One question though: there are a few DOM diffing libraries out there (morphdom, nanomorph, ...); how does your `diff` compare to them?

**Comment by cferdinandi** [comment]
I haven't looked at any other DOM diffing libraries, and am not particularly inclined to, so I can't really say.
