### ISSUE TITLE
App is rendered even though app.render() is commented out

### ISSUE THREAD

**Issue by FilipLundby** [cferdinandi/reef#91]
Brilliant library! Thank you :) 

I can't figure out whether this is intended behavior or not: When I set `store.data.msg` in the load event, the app is rendered even though I haven't specifically called `app.render()`. 

My idea is to load all data into the store through external API's - and then when all is done I'll call `app.render()`. This might not be the best approach and maybe I will reconsider. Nevertheless I'm a bit puzzled about the result of setting store data.

Demo: https://codepen.io/skooterkurt/pen/abBOoXa

```
var store = new Reef.Store({
    data: {
        msg: "",
    }
});

var app = new Reef('#app', {
    store,
    template: props => {
        return `
            <div>${props.msg}</div>
        `
    }
});

window.addEventListener('load', () => {
    store.data.msg = "Message in a bottle"; // <-- The app renders because of this line
})

// app.render();
```

**Comment by cferdinandi** [comment]
In Reef, the `data` object, whether it's on a specific component or in a data store, is reactive by default.

That means that if you set the value of the `data` or any of its properties, it will render a UI update (on the component, or for a store, any components that are using it).

If you need to non-reactively update data, you can make an immutable copy and work with it using the technique described here: https://reefjs.com/state-management/#non-reactive-data

However, the value of the `store.data` will be unchanged with this approach. Updating it will trigger a reactive UI update.

**Can I learn more about the use case here?** There may be a feature I could bake in to help address it, if needed.

(And thank you for the kind words!)

**Comment by FilipLundby** [comment]
Right, I see. I will try that out. 

My goal is to retrieve routes from one endpoint and ID's of all components from another endpoint. Each route will contain the ID of the associated component, e.g.: 

``` 
{
	id: 'about',
	title: 'About',
	url: '/about',
	componentId: 1234
}
``` 

... and the list of components will look like: 

``` 
{ 
	components: 
	[
		{ id: 1234, name: "coolComponent" },
		{ id: 1235, name: "awesomeComponent" },
		{ id: 1236, name: "niceComponent" },
	]
}
``` 

Then whenever the user changes route, I will look up the ID in the store and append the matching component using `addComponent(...)` 

The issue occurred when I retrieve the list of components and adding them to the store, but I also need to ensure routes are ready before rendering anything.

It is working - sort of. Only two issues left - the one mentioned above (I'll test your suggestion) - and also it seem that I need at least 1 default route (before calling the endpoint) otherwise I get a console error. I haven't had time to look into the last part and I'm still getting trying to get familiar with your library, so I might just be some minor thing I'm missed ;) 

Thank you for the quick reply!

**Comment by FilipLundby** [comment]
> The issue occurred when I retrieve the list of components and adding them to the store, but I also need to ensure routes are ready before rendering anything.

I think if forgot to add: "... otherwise the content might flicker a bit until everything is loaded".

Anyway, you explanation made sense. In this case shouldn't need `clone`, instead it seems like a matter of order of execution: first add routes, then save component types to the store. 

I might open a new issue regarding the "1 default route", when I get more time :)
