### ISSUE TITLE
Getters (with parameter)

### ISSUE THREAD

**Issue by hovancik** [cferdinandi/reef#97]
Hi,

small bug on website, on Setters: it says "Try working with setter functions on CodePen →" but links to example without any https://codepen.io/cferdinandi/pen/LYbVwMy

Also, it is not possible to have Getters with param? https://codepen.io/hovancik/pen/dyOGmbK?editors=1111

My usecase: I have a reminders in data and would like to get reminder based on name, so I would like to pass a name to a getter.

**Comment by cferdinandi** [comment]
Fixed the demo, thanks. And yea, that's kind of silly, huh?

I'll add support for that.

**Comment by cferdinandi** [comment]
This is now supported in v8.2.x
